# Run Easy_HCR and check probe pair quality

This notebook is used to run Easy_HCR and then check the quality of the probe pairs (PP) generated.
In order to run this notebook you **need to first adapt some file names** (noted To_be_adapted in the cells) and then you can **click on the double arrow button** at the top left of the notebook. This will then **run automatically everything** and will **stop** at certain steps so you can **make a decision** on some parameters. In that case you never need to run a cell (grey rectangle in the code) yourself, they are executed automatically one by one.

You can also **run it step by step** if you **select the cell and click on the single arrow** on the top left of the notebook. In that case you need to **redo this for every cell of the notebook**.

For more information on Easy_HCR refer to the [website](https://gitlab.com/NCDRlab/easy_hcr)

In [77]:
import pandas as pd
import numpy as np
import csv
import subprocess
import gzip
import math
from insitu_probe_generator.maker37cb import maker
from insitu_probe_generator.start import start
from Bio import SearchIO
from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio.Blast import NCBIXML
from pathlib import Path

In [142]:
# Set the quality control parameters for the probeset
# if you do not want to remove the GC's you can set 'remove_gc' to 'False'
# if you want a more relaxed search for your blast analysis you can set 'stringent_blast_search' to 'False'

remove_gc = True
probepair_number_cutoff = 33
blast_on_genome = True

stringent_transcriptome = input("Do you want to do a stringent blast search against the transcriptome? (Y/N): \n This will make the blast search more strict to find hits in the transcriptome so you will find less problematic probes.\n The default is False but if too many probes are found I suggest to set this parameter to True.").strip().upper()
if stringent_transcriptome == "Y":
    stringent_blast_search = True
    print("\nThe transcriptome search will be stringent.\n")
else:
    stringent_blast_search = False
    print("\nThe transcriptome search will not be stringent.\n")
        
stringent_genome = input("Do you want to do a stringent blast search against the genome? (Y/N): \n This will make the blast search more strict to find hits in the transcriptome so you will find less problematic probes.\n The default is False but if too many probes are found I suggest to set this parameter to True.").strip().upper()
if stringent_genome == "Y":
    stringent_selection = True
    print("\nThe blast search against the genome will be stringent.")
else:
    stringent_selection = False
    print("\nThe blast search against the genome will not be stringent")

Do you want to do a stringent blast search against the transcriptome? (Y/N):
 This will make the blast search more strict to find hits in the transcriptome so you will find less problematic probes.
 The default is False but if too many probes are found I suggest to set this parameter to True. Y

The transcriptome search will be stringent.

Do you want to do a stringent blast search against the genome? (Y/N):
 This will make the blast search more strict to find hits in the transcriptome so you will find less problematic probes.
 The default is False but if too many probes are found I suggest to set this parameter to True. Y

The blast search against the genome will be stringent.

In [ ]:
# Create an output directory

Path("output").mkdir(parents=True, exist_ok=True)

In [144]:
# Run the probe generator

strt = start()
name,fullseq,amplifier,pause,choose,polyAT,polyCG,BlastProbes,db,dropout,show,report,maxprobe,numbr = strt[0],strt[1],strt[2],strt[3],strt[4],strt[5],strt[6],strt[7],strt[8],strt[9],strt[10],strt[11],strt[12],strt[13]
string_output = maker(name,fullseq,amplifier,pause,choose,polyAT,polyCG,BlastProbes,db,dropout,show,report,maxprobe,numbr)

What is the gene name? (ex. eGFP)  LOC112557455
Enter the sense sequence of your cDNA without spaces or returns.  ATGGACGGGCTGGAGCAAGAGATGGTCGGCAAGTCGGCCTTCATGGAGCTGCAGCAACAACAGATCCCACCCGGCATGGCGCACCCGGCCTACCCGTCCATTCGGGCAGGGTATCCGACGCAGCATCACCAGCACGAAAGTGTGTTTTCTGCTCCCCAACACGGCAGGGGCCACCTTGGCTACCCGTTTGCTGCGATGAATTCCATGGGCCCACCCGGATATAATGCCCTCCCACATTTTCCTATGTCGCCGTACCAGACTCCATCGCCACCAAGAGATGACAAAAGTCAAGTGGAGGAGCAGCTTAGAATCAATGGCAAGGGGAAAAAGATGCGAAAACCGCGGACCATATACTCCAGTCTCCAACTCCAGCAGCTGAACAGACGCTTCCAGAGGACGCAGTACCTGGCTCTTCCCGAGCGCGCGGAGCTGGCGGCGTCCCTCGGACTCACCCAGACCCAGGTTAAGATATGGTTTCAAAACCGTCGCTCCAAGTACAAGAAAATAATGAAGCAAGGCGGCACCCCACCCGGAAGCGTCGGTCAGCCAGGACCCGGGGGCCAGCCCTCCAACCCTCCACTTCCTCCCAACTCTCCGACCCTGCAGCACACGCCACCACAGCACCAGGGGCCCCCAGCTCCGCCCCCTCCAAACCAGCAGCAACAGCCGGGACAGTCACCCCAGGGAGACATGCACCCCCAACAGCCGGGCACTCCCCACCAGCAACATCAGCCGTCCGTGTGCCCTCCGCCGGGCTCCAGCGCCGGAAATCACGTCAGCCAGTCCAGCGGCTCCATGATGCCGGTGTCGTCGTCCTCCCTGAGTCCGCAGCCGGCGTGCACGTGGTCCGACATGCACGTGCAGCAGAACGCTGCGGCTGTCAACTCCTACATGTCTCACTACTCCTGGTACACACAGGGCTCCATGCCCACCAGCAGTCGCTGCTGA
What is the amplifier to be used with this probe set? B1,B2,B3,B4,B5,B7,B9,B10,B11,B13,B14,B15,or B17   B5
How many bases from 5' end of the Sense RNA before starting to hybridize? ex. 100  2
What is the max acceptable length for polyA or polyT homopolymers?  5
What is the max acceptable length for polyC or polyG homopolymers?  5
Do you want to choose program options?  Y -or- N  N

HCR3.0 Probe Maker Output version 2021_0.3.2
https://doi.org/10.5281/zenodo.3871970

Written by Ryan W Null - ORCID_0000-0002-3830-4152
 with M. Desmond Ramirez - ORCID_0000-0003-3873-6999
Dennis Sun - ORCID_0000-0003-1000-7276
 and B. Duygu Ozpolat - ORCID_0000-0002-1900-965X

Copyright 2019-2021  The Ozpolat Lab,  https://bduyguozpolat.org/
 with licensing provided under GPL 3.0

For more information visit:
 https://github.com/rwnull/insitu_probe_generator





2026-07-08



From the given parameters, we were able to make 17 probe pairs.


Below is in IDT oPool submission_format.
Copy and Paste the lines below into an XLSX file for submission to IDT starting from 'Pool name'.

Pool name, Sequence
B5_LOC112557455_17_Dla2,CTCACTCCCAATCTCTATaaGCCCTGTGTGTACCAGGAGTAGTGA
B5_LOC112557455_17_Dla2,TCAGCAGCGACTGCTGGTGGGCATGaaCTACCCTACAAATCCAAT
B5_LOC112557455_17_Dla2,CTCACTCCCAATCTCTATaaTGCTGCACGTGCATGTCGGACCACG
B5_LOC112557455_17_Dla2,ATGTAGGAGTTGACAGCCGCAGCGTaaCTACCCTACAAATCCAAT
B5_LOC112557455_17_Dla2,CTCACTCCCAATCTCTATaaACGACACCGGCATCATGGAGCCGCT
B5_LOC112557455_17_Dla2,ACGCCGGCTGCGGACTCAGGGAGGAaaCTACCCTACAAATCCAAT
B5_LOC112557455_17_Dla2,CTCACTCCCAATCTCTATaaGCCCGGCGGAGGGCACACGGACGGC
B5_LOC112557455_17_Dla2,CTGGCTGACGTGATTTCCGGCGCTGaaCTACCCTACAAATCCAAT
B5_LOC112557455_17_Dla2,CTCACTCCCAATCTCTATaaTGGGGGTGCATGTCTCCCTGGGGTG
B5_LOC112557455_17_Dla2,TGTTGCTGGTGGGGAGTGCCCGGCTaaCTACCCTACAAATCCAAT
B5_LOC112557455_17_Dla2,CTCACTCCCAATCTCTATaaGGGGCGGAGCTGGGGGCCCCTGGTG
B5_LOC112557455_17_Dla2,GTCCCGGCTGTTGCTGCTGGTTTGGaaCTACCCTACAAATCCAAT
B5_LOC112557455_17_Dla2,CTCACTCCCAATCTCTATaaGTTGGGAGGAAGTGGAGGGTTGGAG
B5_LOC112557455_17_Dla2,TGGTGGCGTGTGCTGCAGGGTCGGAaaCTACCCTACAAATCCAAT
B5_LOC112557455_17_Dla2,CTCACTCCCAATCTCTATaaCTTCCGGGTGGGGTGCCGCCTTGCT
B5_LOC112557455_17_Dla2,TGGCCCCCGGGTCCTGGCTGACCGAaaCTACCCTACAAATCCAAT
B5_LOC112557455_17_Dla2,CTCACTCCCAATCTCTATaaTTTGAAACCATATCTTAACCTGGGT
B5_LOC112557455_17_Dla2,TTATTTTCTTGTACTTGGAGCGACGaaCTACCCTACAAATCCAAT
B5_LOC112557455_17_Dla2,CTCACTCCCAATCTCTATaaCGCGCGCTCGGGAAGAGCCAGGTAC
B5_LOC112557455_17_Dla2,GGTGAGTCCGAGGGACGCCGCCAGCaaCTACCCTACAAATCCAAT
B5_LOC112557455_17_Dla2,CTCACTCCCAATCTCTATaaTGGAGTTGGAGACTGGAGTATATGG
B5_LOC112557455_17_Dla2,GTCCTCTGGAAGCGTCTGTTCAGCTaaCTACCCTACAAATCCAAT
B5_LOC112557455_17_Dla2,CTCACTCCCAATCTCTATaaCATTGATTCTAAGCTGCTCCTCCAC
B5_LOC112557455_17_Dla2,GCGGTTTTCGCATCTTTTTCCCCTTaaCTACCCTACAAATCCAAT
B5_LOC112557455_17_Dla2,CTCACTCCCAATCTCTATaaAGTCTGGTACGGCGACATAGGAAAA
B5_LOC112557455_17_Dla2,ACTTTTGTCATCTCTTGGTGGCGATaaCTACCCTACAAATCCAAT
B5_LOC112557455_17_Dla2,CTCACTCCCAATCTCTATaaATGGAATTCATCGCAGCAAACGGGT
B5_LOC112557455_17_Dla2,GGGAGGGCATTATATCCGGGTGGGCaaCTACCCTACAAATCCAAT
B5_LOC112557455_17_Dla2,CTCACTCCCAATCTCTATaaCAGAAAACACACTTTCGTGCTGGTG
B5_LOC112557455_17_Dla2,CAAGGTGGCCCCTGCCGTGTTGGGGaaCTACCCTACAAATCCAAT
B5_LOC112557455_17_Dla2,CTCACTCCCAATCTCTATaaCGGGTAGGCCGGGTGCGCCATGCCG
B5_LOC112557455_17_Dla2,CTGCGTCGGATACCCTGCCCGAATGaaCTACCCTACAAATCCAAT
B5_LOC112557455_17_Dla2,CTCACTCCCAATCTCTATaaAAGGCCGACTTGCCGACCATCTCTT
B5_LOC112557455_17_Dla2,GGGATCTGTTGTTGCTGCAGCTCCAaaCTACCCTACAAATCCAAT


Figure Layout of Probe Sequences:

B5_LOC112557455_PP17_Dla2
Pair#  Initiator  Spacer  Probe  Probe  Spacer  Initiator
1   CTCACTCCCAATCTCTAT   aa   GCCCTGTGTGTACCAGGAGTAGTGA     TCAGCAGCGACTGCTGGTGGGCATG   aa   CTACCCTACAAATCCAAT
2   CTCACTCCCAATCTCTAT   aa   TGCTGCACGTGCATGTCGGACCACG     ATGTAGGAGTTGACAGCCGCAGCGT   aa   CTACCCTACAAATCCAAT
3   CTCACTCCCAATCTCTAT   aa   ACGACACCGGCATCATGGAGCCGCT     ACGCCGGCTGCGGACTCAGGGAGGA   aa   CTACCCTACAAATCCAAT
4   CTCACTCCCAATCTCTAT   aa   GCCCGGCGGAGGGCACACGGACGGC     CTGGCTGACGTGATTTCCGGCGCTG   aa   CTACCCTACAAATCCAAT
5   CTCACTCCCAATCTCTAT   aa   TGGGGGTGCATGTCTCCCTGGGGTG     TGTTGCTGGTGGGGAGTGCCCGGCT   aa   CTACCCTACAAATCCAAT
6   CTCACTCCCAATCTCTAT   aa   GGGGCGGAGCTGGGGGCCCCTGGTG     GTCCCGGCTGTTGCTGCTGGTTTGG   aa   CTACCCTACAAATCCAAT
7   CTCACTCCCAATCTCTAT   aa   GTTGGGAGGAAGTGGAGGGTTGGAG     TGGTGGCGTGTGCTGCAGGGTCGGA   aa   CTACCCTACAAATCCAAT
8   CTCACTCCCAATCTCTAT   aa   CTTCCGGGTGGGGTGCCGCCTTGCT     TGGCCCCCGGGTCCTGGCTGACCGA   aa   CTACCCTACAAATCCAAT
9   CTCACTCCCAATCTCTAT   aa   TTTGAAACCATATCTTAACCTGGGT     TTATTTTCTTGTACTTGGAGCGACG   aa   CTACCCTACAAATCCAAT
10   CTCACTCCCAATCTCTAT   aa   CGCGCGCTCGGGAAGAGCCAGGTAC     GGTGAGTCCGAGGGACGCCGCCAGC   aa   CTACCCTACAAATCCAAT
11   CTCACTCCCAATCTCTAT   aa   TGGAGTTGGAGACTGGAGTATATGG     GTCCTCTGGAAGCGTCTGTTCAGCT   aa   CTACCCTACAAATCCAAT
12   CTCACTCCCAATCTCTAT   aa   CATTGATTCTAAGCTGCTCCTCCAC     GCGGTTTTCGCATCTTTTTCCCCTT   aa   CTACCCTACAAATCCAAT
13   CTCACTCCCAATCTCTAT   aa   AGTCTGGTACGGCGACATAGGAAAA     ACTTTTGTCATCTCTTGGTGGCGAT   aa   CTACCCTACAAATCCAAT
14   CTCACTCCCAATCTCTAT   aa   ATGGAATTCATCGCAGCAAACGGGT     GGGAGGGCATTATATCCGGGTGGGC   aa   CTACCCTACAAATCCAAT
15   CTCACTCCCAATCTCTAT   aa   CAGAAAACACACTTTCGTGCTGGTG     CAAGGTGGCCCCTGCCGTGTTGGGG   aa   CTACCCTACAAATCCAAT
16   CTCACTCCCAATCTCTAT   aa   CGGGTAGGCCGGGTGCGCCATGCCG     CTGCGTCGGATACCCTGCCCGAATG   aa   CTACCCTACAAATCCAAT
17   CTCACTCCCAATCTCTAT   aa   AAGGCCGACTTGCCGACCATCTCTT     GGGATCTGTTGTTGCTGCAGCTCCA   aa   CTACCCTACAAATCCAAT




Below are the hybridizing sequences and where they align to the cDNA:

Pair#  cDNAcoord  Probe  cDNAcoord  cDNAcoord  Probe  cDNAcoord
17   68   GGGATCTGTTGTTGCTGCAGCTCCA   43     41   AAGGCCGACTTGCCGACCATCTCTT   16
16   123   CTGCGTCGGATACCCTGCCCGAATG   98     96   CGGGTAGGCCGGGTGCGCCATGCCG   71
15   178   CAAGGTGGCCCCTGCCGTGTTGGGG   153     151   CAGAAAACACACTTTCGTGCTGGTG   126
14   233   GGGAGGGCATTATATCCGGGTGGGC   208     206   ATGGAATTCATCGCAGCAAACGGGT   181
13   288   ACTTTTGTCATCTCTTGGTGGCGAT   263     261   AGTCTGGTACGGCGACATAGGAAAA   236
12   343   GCGGTTTTCGCATCTTTTTCCCCTT   318     316   CATTGATTCTAAGCTGCTCCTCCAC   291
11   398   GTCCTCTGGAAGCGTCTGTTCAGCT   373     371   TGGAGTTGGAGACTGGAGTATATGG   346
10   453   GGTGAGTCCGAGGGACGCCGCCAGC   428     426   CGCGCGCTCGGGAAGAGCCAGGTAC   401
9   508   TTATTTTCTTGTACTTGGAGCGACG   483     481   TTTGAAACCATATCTTAACCTGGGT   456
8   563   TGGCCCCCGGGTCCTGGCTGACCGA   538     536   CTTCCGGGTGGGGTGCCGCCTTGCT   511
7   618   TGGTGGCGTGTGCTGCAGGGTCGGA   593     591   GTTGGGAGGAAGTGGAGGGTTGGAG   566
6   673   GTCCCGGCTGTTGCTGCTGGTTTGG   648     646   GGGGCGGAGCTGGGGGCCCCTGGTG   621
5   728   TGTTGCTGGTGGGGAGTGCCCGGCT   703     701   TGGGGGTGCATGTCTCCCTGGGGTG   676
4   783   CTGGCTGACGTGATTTCCGGCGCTG   758     756   GCCCGGCGGAGGGCACACGGACGGC   731
3   838   ACGCCGGCTGCGGACTCAGGGAGGA   813     811   ACGACACCGGCATCATGGAGCCGCT   786
2   893   ATGTAGGAGTTGACAGCCGCAGCGT   868     866   TGCTGCACGTGCATGTCGGACCACG   841
1   948   TCAGCAGCGACTGCTGGTGGGCATG   923     921   GCCCTGTGTGTACCAGGAGTAGTGA   896




This is the in-place localization of the probe pairs along the full-length sense cDNA.

>LOC112557455 Sense Strand
nnnnnnnnnnnnnnnnAAGAGATGGTCGGCAAGTCGGCCTTnnTGGAGCTGCAGCAACAACAGATCCCnnnCGGCATGGCGCACCCGGCCTACCCGnnCATTCGGGCAGGGTATCCGACGCAGnnnCACCAGCACGAAAGTGTGTTTTCTGnnCCCCAACACGGCAGGGGCCACCTTGnnnACCCGTTTGCTGCGATGAATTCCATnnGCCCACCCGGATATAATGCCCTCCCnnnTTTTCCTATGTCGCCGTACCAGACTnnATCGCCACCAAGAGATGACAAAAGTnnnGTGGAGGAGCAGCTTAGAATCAATGnnAAGGGGAAAAAGATGCGAAAACCGCnnnCCATATACTCCAGTCTCCAACTCCAnnAGCTGAACAGACGCTTCCAGAGGACnnnGTACCTGGCTCTTCCCGAGCGCGCGnnGCTGGCGGCGTCCCTCGGACTCACCnnnACCCAGGTTAAGATATGGTTTCAAAnnCGTCGCTCCAAGTACAAGAAAATAAnnnAGCAAGGCGGCACCCCACCCGGAAGnnTCGGTCAGCCAGGACCCGGGGGCCAnnnCTCCAACCCTCCACTTCCTCCCAACnnTCCGACCCTGCAGCACACGCCACCAnnnCACCAGGGGCCCCCAGCTCCGCCCCnnCCAAACCAGCAGCAACAGCCGGGACnnnCACCCCAGGGAGACATGCACCCCCAnnAGCCGGGCACTCCCCACCAGCAACAnnnGCCGTCCGTGTGCCCTCCGCCGGGCnnCAGCGCCGGAAATCACGTCAGCCAGnnnAGCGGCTCCATGATGCCGGTGTCGTnnTCCTCCCTGAGTCCGCAGCCGGCGTnnnCGTGGTCCGACATGCACGTGCAGCAnnACGCTGCGGCTGTCAACTCCTACATnnnTCACTACTCCTGGTACACACAGGGCnnCATGCCCACCAGCAGTCGCTGCTGA




Anti-sense sequence used to create probes:

>LOC112557455 Anti-Sense Strand
TCAGCAGCGACTGCTGGTGGGCATGGAGCCCTGTGTGTACCAGGAGTAGTGAGACATGTAGGAGTTGACAGCCGCAGCGTTCTGCTGCACGTGCATGTCGGACCACGTGCACGCCGGCTGCGGACTCAGGGAGGACGACGACACCGGCATCATGGAGCCGCTGGACTGGCTGACGTGATTTCCGGCGCTGGAGCCCGGCGGAGGGCACACGGACGGCTGATGTTGCTGGTGGGGAGTGCCCGGCTGTTGGGGGTGCATGTCTCCCTGGGGTGACTGTCCCGGCTGTTGCTGCTGGTTTGGAGGGGGCGGAGCTGGGGGCCCCTGGTGCTGTGGTGGCGTGTGCTGCAGGGTCGGAGAGTTGGGAGGAAGTGGAGGGTTGGAGGGCTGGCCCCCGGGTCCTGGCTGACCGACGCTTCCGGGTGGGGTGCCGCCTTGCTTCATTATTTTCTTGTACTTGGAGCGACGGTTTTGAAACCATATCTTAACCTGGGTCTGGGTGAGTCCGAGGGACGCCGCCAGCTCCGCGCGCTCGGGAAGAGCCAGGTACTGCGTCCTCTGGAAGCGTCTGTTCAGCTGCTGGAGTTGGAGACTGGAGTATATGGTCCGCGGTTTTCGCATCTTTTTCCCCTTGCCATTGATTCTAAGCTGCTCCTCCACTTGACTTTTGTCATCTCTTGGTGGCGATGGAGTCTGGTACGGCGACATAGGAAAATGTGGGAGGGCATTATATCCGGGTGGGCCCATGGAATTCATCGCAGCAAACGGGTAGCCAAGGTGGCCCCTGCCGTGTTGGGGAGCAGAAAACACACTTTCGTGCTGGTGATGCTGCGTCGGATACCCTGCCCGAATGGACGGGTAGGCCGGGTGCGCCATGCCGGGTGGGATCTGTTGTTGCTGCAGCTCCATGAAGGCCGACTTGCCGACCATCTCTTGCTCCAGCCCGTCCAT




References:

 See Choi et al. 2018 Development for HCR3.0 methodology details
 https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6031405/

 See Wang et al. 2020 BioRxiv for expanded amplifier information
 https://www.biorxiv.org/content/10.1101/274456v3

In [145]:
gene_name = name
amplifier = amplifier

In [ ]:
# Save the generated probes as CSV file

csv_path = f"output/{name}_probes.csv"

probe_file = open(csv_path, "w")
n = probe_file.write(string_output)
probe_file.close()

# Read the csv back in as table

df = pd.read_csv(
    f"output/{name}_probes.csv",
    index_col=0,
)
print("Gene: ", gene_name)
print("Amplifier: ", amplifier)
print("Probes:")
df.head()

Gene:  LOC112557455
Amplifier:  B5
Probes:

                Initiator Spacer                      Probe                    Probe.1 Spacer.1         Initiator.1
Pair#
1      CTCACTCCCAATCTCTAT     aa  GCCCTGTGTGTACCAGGAGTAGTGA  TCAGCAGCGACTGCTGGTGGGCATG       aa  CTACCCTACAAATCCAAT
2      CTCACTCCCAATCTCTAT     aa  TGCTGCACGTGCATGTCGGACCACG  ATGTAGGAGTTGACAGCCGCAGCGT       aa  CTACCCTACAAATCCAAT
3      CTCACTCCCAATCTCTAT     aa  ACGACACCGGCATCATGGAGCCGCT  ACGCCGGCTGCGGACTCAGGGAGGA       aa  CTACCCTACAAATCCAAT
4      CTCACTCCCAATCTCTAT     aa  GCCCGGCGGAGGGCACACGGACGGC  CTGGCTGACGTGATTTCCGGCGCTG       aa  CTACCCTACAAATCCAAT
5      CTCACTCCCAATCTCTAT     aa  TGGGGGTGCATGTCTCCCTGGGGTG  TGTTGCTGGTGGGGAGTGCCCGGCT       aa  CTACCCTACAAATCCAAT

In [147]:
# Generate probe identifiers

probe_identifiers = [gene_name + "_PP_" + str(n + 1) for n,_ in enumerate(df.iterrows())]
probe_identifiers = [f"{gene_name}_{amplifier}_PP_{str(n + 1)}" for n,_ in enumerate(df.iterrows())]
df.index = probe_identifiers
df.head()

                               Initiator Spacer                      Probe                    Probe.1 Spacer.1         Initiator.1
LOC112557455_B5_PP_1  CTCACTCCCAATCTCTAT     aa  GCCCTGTGTGTACCAGGAGTAGTGA  TCAGCAGCGACTGCTGGTGGGCATG       aa  CTACCCTACAAATCCAAT
LOC112557455_B5_PP_2  CTCACTCCCAATCTCTAT     aa  TGCTGCACGTGCATGTCGGACCACG  ATGTAGGAGTTGACAGCCGCAGCGT       aa  CTACCCTACAAATCCAAT
LOC112557455_B5_PP_3  CTCACTCCCAATCTCTAT     aa  ACGACACCGGCATCATGGAGCCGCT  ACGCCGGCTGCGGACTCAGGGAGGA       aa  CTACCCTACAAATCCAAT
LOC112557455_B5_PP_4  CTCACTCCCAATCTCTAT     aa  GCCCGGCGGAGGGCACACGGACGGC  CTGGCTGACGTGATTTCCGGCGCTG       aa  CTACCCTACAAATCCAAT
LOC112557455_B5_PP_5  CTCACTCCCAATCTCTAT     aa  TGGGGGTGCATGTCTCCCTGGGGTG  TGTTGCTGGTGGGGAGTGCCCGGCT       aa  CTACCCTACAAATCCAAT

In [148]:
# Check GC-ending probes for later
# GC and the end for the forst probe and GC at the start for the second

df["GC_QC"] = df["Probe"].str.endswith("GC") | df["Probe"].str.endswith("CG") | df["Probe.1"].str.startswith("GC") | df["Probe.1"].str.startswith("CG")
print("Number of probe pairs:", len(df))
print(f"{len(df.loc[df.GC_QC == True])} GC probe pairs")
print(f"Kept {len(df.loc[df.GC_QC != True])} no-GC probe pairs")
df.head()

Number of probe pairs: 17
4 GC probe pairs
Kept 13 no-GC probe pairs

                               Initiator Spacer                      Probe                    Probe.1 Spacer.1         Initiator.1  GC_QC
LOC112557455_B5_PP_1  CTCACTCCCAATCTCTAT     aa  GCCCTGTGTGTACCAGGAGTAGTGA  TCAGCAGCGACTGCTGGTGGGCATG       aa  CTACCCTACAAATCCAAT  False
LOC112557455_B5_PP_2  CTCACTCCCAATCTCTAT     aa  TGCTGCACGTGCATGTCGGACCACG  ATGTAGGAGTTGACAGCCGCAGCGT       aa  CTACCCTACAAATCCAAT   True
LOC112557455_B5_PP_3  CTCACTCCCAATCTCTAT     aa  ACGACACCGGCATCATGGAGCCGCT  ACGCCGGCTGCGGACTCAGGGAGGA       aa  CTACCCTACAAATCCAAT  False
LOC112557455_B5_PP_4  CTCACTCCCAATCTCTAT     aa  GCCCGGCGGAGGGCACACGGACGGC  CTGGCTGACGTGATTTCCGGCGCTG       aa  CTACCCTACAAATCCAAT   True
LOC112557455_B5_PP_5  CTCACTCCCAATCTCTAT     aa  TGGGGGTGCATGTCTCCCTGGGGTG  TGTTGCTGGTGGGGAGTGCCCGGCT       aa  CTACCCTACAAATCCAAT  False

In [149]:
# Generate BLAST sequences

df["blast"] = df["Probe"] + "NN" + df["Probe.1"]
df.head()

                               Initiator Spacer                      Probe                    Probe.1 Spacer.1         Initiator.1  GC_QC                                              blast
LOC112557455_B5_PP_1  CTCACTCCCAATCTCTAT     aa  GCCCTGTGTGTACCAGGAGTAGTGA  TCAGCAGCGACTGCTGGTGGGCATG       aa  CTACCCTACAAATCCAAT  False  GCCCTGTGTGTACCAGGAGTAGTGANNTCAGCAGCGACTGCTGGTG...
LOC112557455_B5_PP_2  CTCACTCCCAATCTCTAT     aa  TGCTGCACGTGCATGTCGGACCACG  ATGTAGGAGTTGACAGCCGCAGCGT       aa  CTACCCTACAAATCCAAT   True  TGCTGCACGTGCATGTCGGACCACGNNATGTAGGAGTTGACAGCCG...
LOC112557455_B5_PP_3  CTCACTCCCAATCTCTAT     aa  ACGACACCGGCATCATGGAGCCGCT  ACGCCGGCTGCGGACTCAGGGAGGA       aa  CTACCCTACAAATCCAAT  False  ACGACACCGGCATCATGGAGCCGCTNNACGCCGGCTGCGGACTCAG...
LOC112557455_B5_PP_4  CTCACTCCCAATCTCTAT     aa  GCCCGGCGGAGGGCACACGGACGGC  CTGGCTGACGTGATTTCCGGCGCTG       aa  CTACCCTACAAATCCAAT   True  GCCCGGCGGAGGGCACACGGACGGCNNCTGGCTGACGTGATTTCCG...
LOC112557455_B5_PP_5  CTCACTCCCAATCTCTAT     aa  TGGGGGTGCATGTCTCCCTGGGGTG  TGTTGCTGGTGGGGAGTGCCCGGCT       aa  CTACCCTACAAATCCAAT  False  TGGGGGTGCATGTCTCCCTGGGGTGNNTGTTGCTGGTGGGGAGTGC...

In [ ]:
# Create a simple dataframes for BLAST

df_blast = pd.DataFrame(df.index.values, columns=["Identifier"])
df_blast["Probe"] = df.blast.values
df_blast.to_csv(f"output/{gene_name}_probes.txt",sep='\t',index=False,header=False, quoting=csv.QUOTE_NONE)
df_blast.head()

             Identifier                                              Probe
0  LOC112557455_B5_PP_1  GCCCTGTGTGTACCAGGAGTAGTGANNTCAGCAGCGACTGCTGGTG...
1  LOC112557455_B5_PP_2  TGCTGCACGTGCATGTCGGACCACGNNATGTAGGAGTTGACAGCCG...
2  LOC112557455_B5_PP_3  ACGACACCGGCATCATGGAGCCGCTNNACGCCGGCTGCGGACTCAG...
3  LOC112557455_B5_PP_4  GCCCGGCGGAGGGCACACGGACGGCNNCTGGCTGACGTGATTTCCG...
4  LOC112557455_B5_PP_5  TGGGGGTGCATGTCTCCCTGGGGTGNNTGTTGCTGGTGGGGAGTGC...

In [151]:
# Generate a list of SeqRecord to write a fasta file

probe_sequences = [SeqRecord(Seq(probe), id=id) for probe, id in zip(df_blast.Probe.values, df_blast.Identifier.values)]

In [ ]:
# Create a fasta file containing the probe's sequences in the output folder (create this output folder in the same folder as the probe generator)

fasta_path = f"output/{gene_name}_to_blast_against_transcriptome.fasta"

with open(fasta_path, "w") as output_handle:
    for record in probe_sequences:
        SeqIO.write(record, output_handle, "fasta")

fasta_path

'output_snail/LOC112557455_to_blast_against_canaliculata_transcriptome.fasta'

In [ ]:
# Extract the position (chromosome, start position and end position) of the transcript of interest in the genome of your species.
# This step is needed for later steps

gtf_path = "To_be_adapted.gtf.gz" # Here put the path to the annotation GTF file (make sure you have it in your Easy_HCR folder)
target_length = len(fullseq)

# The length of the transcript in the transcript FASTA file correspond to the cumulative size of each exon of a transcript in the annotation GTF file.

# We first create a dictionnary to store the cumulative size of the exons of each transcript.
transcript_data = {}

with gzip.open(gtf_path, "rt") as f:
    for line in f:
        if line.startswith("#"): continue
        columns = line.split("\t")
        
        # On ne traite que les lignes 'exon' qui contiennent le nom du gène
        if len(columns) > 8 and columns[2] == "exon" and gene_name in line:
            # Extraction de l'ID du transcrit (souvent transcript_id "ID"; dans la colonne 8)
            # On cherche l'attribut transcript_id pour grouper les exons correctement
            attributes = columns[8]
            t_id = None
            if 'transcript_id "' in attributes:
                t_id = attributes.split('transcript_id "')[1].split('"')[0]
            else:
                # Si pas de transcript_id, on utilise le gene_name comme repli
                t_id = gene_name

            exon_start = int(columns[3])
            exon_end = int(columns[4])
            exon_len = (exon_end - exon_start) + 1
            
            if t_id not in transcript_data:
                transcript_data[t_id] = {
                    "chrom": columns[0],
                    "total_len": 0,
                    "min_start": exon_start,
                    "max_end": exon_end
                }
            
            transcript_data[t_id]["total_len"] += exon_len
            # On garde les bornes génomiques min/max pour le gène
            transcript_data[t_id]["min_start"] = min(transcript_data[t_id]["min_start"], exon_start)
            transcript_data[t_id]["max_end"] = max(transcript_data[t_id]["max_end"], exon_end)

# Then, we search the transcript with the closest length to our sequence of interest.
best_chrom, best_start, best_end = None, None, None
best_t_id = None
min_diff = float('inf')

for t_id, data in transcript_data.items():
    diff = abs(data["total_len"] - target_length)
    if diff < min_diff:
        min_diff = diff
        best_t_id = t_id
        best_chrom = data["chrom"]
        best_start = data["min_start"]
        best_end = data["max_end"]

if best_chrom:
    found_len = transcript_data[best_t_id]["total_len"]
    print(f"Length of the transcript of interest: {target_length} bp")
    print(f"Best matching transcript: {best_t_id}")
    print(f"Position in the genome of your species: {best_chrom}:{best_start}-{best_end}")
else:
    print(f"No exons found for '{gene_name}' in the GTF.")

Length of the transcript of interest: 948 bp
Best matching transcript: XM_025227322.1
Position on P. canaliculata: NC_037591.1:6477697-6509758

In [ ]:
# Create the output path for the blast against your species transcriptome
blast_path = f"output/{gene_name}_blast_against_transcriptome.xml"

In [ ]:
# Create the blast command depending on the chosen mode (stringent or not)

# Define name of the transcriptome database (Don't forget to first run the custom_database_creation.ipynb script on the file)
db_path = "To_be_adapted.fna.gz"

if stringent_blast_search == True:
    cmd_blastn = [
        "blastn",
        "-query", fasta_path,
        "-db", db_path,
        "-evalue", "0.05",
        "-outfmt", "5",
        "-penalty", "-3",
        "-reward", "2",
        "-gapopen", "5",
        "-gapextend", "2",
        "-word_size", "11",
        "-out", blast_path
    ]
else:
    cmd_blastn = [
        "blastn",
        "-query", fasta_path,
        "-db", db_path,
        "-evalue", "0.2",
        "-outfmt", "5",
        "-word_size", "11",
        "-out", blast_path
    ]

In [ ]:
# Run blast

try:
    print(f"Blasting the probes against the transcriptome of your target species...")
    result = subprocess.run(cmd_blastn, capture_output=True, text=True, check=True)
    print("Finished!")
    print(result.stdout) # Print output of blast search
except subprocess.CalledProcessError as e:
    print(f"Error during the blast search : {e.stderr}")

Blasting the probes against the P. canaliculata transcriptome...
Finished!

In [157]:
# Read the xml file containing the results
result_handle = open(blast_path)
blast_records = list(NCBIXML.parse(result_handle))
result_handle.close()

In [158]:
# Print a table listing the blast results grouped per probe pair
# You can check the transcript ids here.

queries = []
names = []

for record in blast_records:
    for alignment in record.alignments:
        queries.append(record.query.split(" ")[0])
        title = alignment.title
        name_parts = title.split("|")
        names.append(name_parts[-1])
    

df_blast_results = pd.DataFrame(queries, columns=["Probe"])
df_blast_results["Name"] = names
df_blast_results

                    Probe                                               Name
0    LOC112557455_B5_PP_1  NC_037591.1_cds_XP_025083107.1_4345 [gene=LOC1...
1    LOC112557455_B5_PP_2  NC_037591.1_cds_XP_025083107.1_4345 [gene=LOC1...
2    LOC112557455_B5_PP_3  NC_037591.1_cds_XP_025083107.1_4345 [gene=LOC1...
3    LOC112557455_B5_PP_4  NC_037591.1_cds_XP_025083107.1_4345 [gene=LOC1...
4    LOC112557455_B5_PP_5  NC_037591.1_cds_XP_025083107.1_4345 [gene=LOC1...
5    LOC112557455_B5_PP_6  NC_037591.1_cds_XP_025083107.1_4345 [gene=LOC1...
6    LOC112557455_B5_PP_7  NC_037591.1_cds_XP_025083107.1_4345 [gene=LOC1...
7    LOC112557455_B5_PP_8  NC_037591.1_cds_XP_025083107.1_4345 [gene=LOC1...
8    LOC112557455_B5_PP_9  NC_037591.1_cds_XP_025083107.1_4345 [gene=LOC1...
9   LOC112557455_B5_PP_10  NC_037591.1_cds_XP_025083107.1_4345 [gene=LOC1...
10  LOC112557455_B5_PP_11  NC_037591.1_cds_XP_025083107.1_4345 [gene=LOC1...
11  LOC112557455_B5_PP_12  NC_037591.1_cds_XP_025083107.1_4345 [gene=LOC1...
12  LOC112557455_B5_PP_13  NC_037591.1_cds_XP_025083107.1_4345 [gene=LOC1...
13  LOC112557455_B5_PP_14  NC_037591.1_cds_XP_025083107.1_4345 [gene=LOC1...
14  LOC112557455_B5_PP_15  NC_037591.1_cds_XP_025083107.1_4345 [gene=LOC1...
15  LOC112557455_B5_PP_16  NC_037591.1_cds_XP_025083107.1_4345 [gene=LOC1...
16  LOC112557455_B5_PP_17  NC_037591.1_cds_XP_025083107.1_4345 [gene=LOC1...

In [159]:
# Print a table that shows the number of hits per probe pair
df_hits = df_blast_results['Probe'].value_counts().reset_index()
df_hits.columns = ['Probe', 'n_hits']
df_hits['Probe'] = df_hits['Probe'].str.split(" ").str[0]
df_hits = df_hits.set_index('Probe')

df_hits

                       n_hits
Probe
LOC112557455_B5_PP_1        1
LOC112557455_B5_PP_2        1
LOC112557455_B5_PP_3        1
LOC112557455_B5_PP_4        1
LOC112557455_B5_PP_5        1
LOC112557455_B5_PP_6        1
LOC112557455_B5_PP_7        1
LOC112557455_B5_PP_8        1
LOC112557455_B5_PP_9        1
LOC112557455_B5_PP_10       1
LOC112557455_B5_PP_11       1
LOC112557455_B5_PP_12       1
LOC112557455_B5_PP_13       1
LOC112557455_B5_PP_14       1
LOC112557455_B5_PP_15       1
LOC112557455_B5_PP_16       1
LOC112557455_B5_PP_17       1

In [ ]:
## Removal of all probes with too many hits in the transcriptome of your species.
# You need to set the numbers to the number of transcripts your gene of interest has.

hit_threshold = int(input("How many transcripts does your gene have? (number): \n This will remove the probe pairs which have more matches than your gene of interest.\n").strip())

to_exclude = df_hits.loc[df_hits.n_hits > hit_threshold].index.values.tolist()
print("Probes to remove:")
print(to_exclude)

How many transcripts does your gene have? (number):
 This will remove the probe pairs which have more matches than your gene of interest.
 1

Probes to remove:
[]

In [161]:
# If you need to manually remove additional probes you can paste the name between the brackets
# This prints the list of the selected probes to be removed

manual_exclude = [
    
]

probes_to_remove = to_exclude + manual_exclude
probes_to_remove

[]

In [162]:
# Remove unwanted probes

on_topic_indexes = [n for n, probe in enumerate(df.index.values) if probe not in probes_to_remove]
df_qc_blast = df.iloc[on_topic_indexes]
print(f"{len(on_topic_indexes)} probes kept:\n", df_qc_blast.index.unique().values)
df_qc_blast.head(10)

17 probes kept:
 ['LOC112557455_B5_PP_1' 'LOC112557455_B5_PP_2' 'LOC112557455_B5_PP_3'
 'LOC112557455_B5_PP_4' 'LOC112557455_B5_PP_5' 'LOC112557455_B5_PP_6'
 'LOC112557455_B5_PP_7' 'LOC112557455_B5_PP_8' 'LOC112557455_B5_PP_9'
 'LOC112557455_B5_PP_10' 'LOC112557455_B5_PP_11' 'LOC112557455_B5_PP_12'
 'LOC112557455_B5_PP_13' 'LOC112557455_B5_PP_14' 'LOC112557455_B5_PP_15'
 'LOC112557455_B5_PP_16' 'LOC112557455_B5_PP_17']

                                Initiator Spacer                      Probe                    Probe.1 Spacer.1         Initiator.1  GC_QC                                              blast
LOC112557455_B5_PP_1   CTCACTCCCAATCTCTAT     aa  GCCCTGTGTGTACCAGGAGTAGTGA  TCAGCAGCGACTGCTGGTGGGCATG       aa  CTACCCTACAAATCCAAT  False  GCCCTGTGTGTACCAGGAGTAGTGANNTCAGCAGCGACTGCTGGTG...
LOC112557455_B5_PP_2   CTCACTCCCAATCTCTAT     aa  TGCTGCACGTGCATGTCGGACCACG  ATGTAGGAGTTGACAGCCGCAGCGT       aa  CTACCCTACAAATCCAAT   True  TGCTGCACGTGCATGTCGGACCACGNNATGTAGGAGTTGACAGCCG...
LOC112557455_B5_PP_3   CTCACTCCCAATCTCTAT     aa  ACGACACCGGCATCATGGAGCCGCT  ACGCCGGCTGCGGACTCAGGGAGGA       aa  CTACCCTACAAATCCAAT  False  ACGACACCGGCATCATGGAGCCGCTNNACGCCGGCTGCGGACTCAG...
LOC112557455_B5_PP_4   CTCACTCCCAATCTCTAT     aa  GCCCGGCGGAGGGCACACGGACGGC  CTGGCTGACGTGATTTCCGGCGCTG       aa  CTACCCTACAAATCCAAT   True  GCCCGGCGGAGGGCACACGGACGGCNNCTGGCTGACGTGATTTCCG...
LOC112557455_B5_PP_5   CTCACTCCCAATCTCTAT     aa  TGGGGGTGCATGTCTCCCTGGGGTG  TGTTGCTGGTGGGGAGTGCCCGGCT       aa  CTACCCTACAAATCCAAT  False  TGGGGGTGCATGTCTCCCTGGGGTGNNTGTTGCTGGTGGGGAGTGC...
LOC112557455_B5_PP_6   CTCACTCCCAATCTCTAT     aa  GGGGCGGAGCTGGGGGCCCCTGGTG  GTCCCGGCTGTTGCTGCTGGTTTGG       aa  CTACCCTACAAATCCAAT  False  GGGGCGGAGCTGGGGGCCCCTGGTGNNGTCCCGGCTGTTGCTGCTG...
LOC112557455_B5_PP_7   CTCACTCCCAATCTCTAT     aa  GTTGGGAGGAAGTGGAGGGTTGGAG  TGGTGGCGTGTGCTGCAGGGTCGGA       aa  CTACCCTACAAATCCAAT  False  GTTGGGAGGAAGTGGAGGGTTGGAGNNTGGTGGCGTGTGCTGCAGG...
LOC112557455_B5_PP_8   CTCACTCCCAATCTCTAT     aa  CTTCCGGGTGGGGTGCCGCCTTGCT  TGGCCCCCGGGTCCTGGCTGACCGA       aa  CTACCCTACAAATCCAAT  False  CTTCCGGGTGGGGTGCCGCCTTGCTNNTGGCCCCCGGGTCCTGGCT...
LOC112557455_B5_PP_9   CTCACTCCCAATCTCTAT     aa  TTTGAAACCATATCTTAACCTGGGT  TTATTTTCTTGTACTTGGAGCGACG       aa  CTACCCTACAAATCCAAT  False  TTTGAAACCATATCTTAACCTGGGTNNTTATTTTCTTGTACTTGGA...
LOC112557455_B5_PP_10  CTCACTCCCAATCTCTAT     aa  CGCGCGCTCGGGAAGAGCCAGGTAC  GGTGAGTCCGAGGGACGCCGCCAGC       aa  CTACCCTACAAATCCAAT  False  CGCGCGCTCGGGAAGAGCCAGGTACNNGGTGAGTCCGAGGGACGCC...

In [163]:
# Remove probes ending in GC or CG

if remove_gc == True:
    orig_number = len(df_qc_blast)
    print("Previous number of probe pairs:", orig_number)
    df_qc_blast = df_qc_blast.loc[df_qc_blast.GC_QC != True]
    print(f"{orig_number - len(df_qc_blast)} probe pairs removed due to GC issues")
    print(f"Updated number of probe pairs:", len(df_qc_blast))
df_qc_blast.head(10)

Previous number of probe pairs: 17
4 probe pairs removed due to GC issues
Updated number of probe pairs: 13

                                Initiator Spacer                      Probe                    Probe.1 Spacer.1         Initiator.1  GC_QC                                              blast
LOC112557455_B5_PP_1   CTCACTCCCAATCTCTAT     aa  GCCCTGTGTGTACCAGGAGTAGTGA  TCAGCAGCGACTGCTGGTGGGCATG       aa  CTACCCTACAAATCCAAT  False  GCCCTGTGTGTACCAGGAGTAGTGANNTCAGCAGCGACTGCTGGTG...
LOC112557455_B5_PP_3   CTCACTCCCAATCTCTAT     aa  ACGACACCGGCATCATGGAGCCGCT  ACGCCGGCTGCGGACTCAGGGAGGA       aa  CTACCCTACAAATCCAAT  False  ACGACACCGGCATCATGGAGCCGCTNNACGCCGGCTGCGGACTCAG...
LOC112557455_B5_PP_5   CTCACTCCCAATCTCTAT     aa  TGGGGGTGCATGTCTCCCTGGGGTG  TGTTGCTGGTGGGGAGTGCCCGGCT       aa  CTACCCTACAAATCCAAT  False  TGGGGGTGCATGTCTCCCTGGGGTGNNTGTTGCTGGTGGGGAGTGC...
LOC112557455_B5_PP_6   CTCACTCCCAATCTCTAT     aa  GGGGCGGAGCTGGGGGCCCCTGGTG  GTCCCGGCTGTTGCTGCTGGTTTGG       aa  CTACCCTACAAATCCAAT  False  GGGGCGGAGCTGGGGGCCCCTGGTGNNGTCCCGGCTGTTGCTGCTG...
LOC112557455_B5_PP_7   CTCACTCCCAATCTCTAT     aa  GTTGGGAGGAAGTGGAGGGTTGGAG  TGGTGGCGTGTGCTGCAGGGTCGGA       aa  CTACCCTACAAATCCAAT  False  GTTGGGAGGAAGTGGAGGGTTGGAGNNTGGTGGCGTGTGCTGCAGG...
LOC112557455_B5_PP_8   CTCACTCCCAATCTCTAT     aa  CTTCCGGGTGGGGTGCCGCCTTGCT  TGGCCCCCGGGTCCTGGCTGACCGA       aa  CTACCCTACAAATCCAAT  False  CTTCCGGGTGGGGTGCCGCCTTGCTNNTGGCCCCCGGGTCCTGGCT...
LOC112557455_B5_PP_9   CTCACTCCCAATCTCTAT     aa  TTTGAAACCATATCTTAACCTGGGT  TTATTTTCTTGTACTTGGAGCGACG       aa  CTACCCTACAAATCCAAT  False  TTTGAAACCATATCTTAACCTGGGTNNTTATTTTCTTGTACTTGGA...
LOC112557455_B5_PP_10  CTCACTCCCAATCTCTAT     aa  CGCGCGCTCGGGAAGAGCCAGGTAC  GGTGAGTCCGAGGGACGCCGCCAGC       aa  CTACCCTACAAATCCAAT  False  CGCGCGCTCGGGAAGAGCCAGGTACNNGGTGAGTCCGAGGGACGCC...
LOC112557455_B5_PP_11  CTCACTCCCAATCTCTAT     aa  TGGAGTTGGAGACTGGAGTATATGG  GTCCTCTGGAAGCGTCTGTTCAGCT       aa  CTACCCTACAAATCCAAT  False  TGGAGTTGGAGACTGGAGTATATGGNNGTCCTCTGGAAGCGTCTGT...
LOC112557455_B5_PP_13  CTCACTCCCAATCTCTAT     aa  AGTCTGGTACGGCGACATAGGAAAA  ACTTTTGTCATCTCTTGGTGGCGAT       aa  CTACCCTACAAATCCAAT  False  AGTCTGGTACGGCGACATAGGAAAANNACTTTTGTCATCTCTTGGT...

In [ ]:
# Determine if you want to blast the remaining probes against the genomes of your target species

blast_genomes = input("Do you want to blast the remaining probes against the genomes of your target species? (Y/N): \nThis will blast the transcript of interest against the genomes to see which regions are problematic\nand then it will blast the remaining probes against the transcript of interest to see which probes align\nin the problematic regions of the transcript.\n").strip().upper()

Do you want to blast the remaining probes against the genomes of O. vulgaris and O. sinensis? (Y/N):
This will blast the transcript of interest against the genomes to see which regions are problematic
and then it will blast the remaining probes against the transcript of interest to see which probes align
in the problematic regions of the transcript.
 Y

In [ ]:
# Create a new fasta file containing the sequences of the remaining probes in the output folder
if blast_genomes == "Y":
    df_blast = pd.DataFrame(df_qc_blast.index.values, columns=["Identifier"])
    df_blast["Probe"] = df_qc_blast.blast.values
    df_blast.to_csv(f"output/{gene_name}_probes.txt",sep='\t',index=False,header=False, quoting=csv.QUOTE_NONE)
    probe_sequences = [SeqRecord(Seq(probe), id=id) for probe, id in zip(df_blast.Probe.values, df_blast.Identifier.values)]
    fasta_path = f"output/{gene_name}_to_blast_against_genome.fasta"
    with open(fasta_path, "w") as output_handle:
        for record in probe_sequences:
            SeqIO.write(record, output_handle, "fasta")

In [ ]:
# Create a fasta file containing the transcript sequence in order to blast it against the genome of your target species
if blast_genomes == "Y":
    file_path = f"output/{gene_name}.fasta"
    with open(file_path, "w") as f:
        f.write(f">{gene_name}\n")
        f.write(f"{fullseq}\n")

In [ ]:
# Align the transcript of interest to genome of your species for extra check
# Load database generated from your species genome (Here again you need to make sure you ran the custom_database_creation.ipynb script on the file)
if blast_genomes == "Y":
    db_path = "To_be_adapted.fna.gz"

    # Define output file name
    blast_path = f"output/{gene_name}_blast_against_genome.xml"

    # Create blast command
    cmd_blastn = [
        "blastn",
        "-query", file_path,
        "-db", db_path,
        "-task", "blastn",
        "-outfmt", "5",
        "-evalue", "0.05",
        "-out", blast_path
    ]

    # Run blast and save the results
    try:
        print(f"Blasting the transcript of interest against the genome of your species...")
        result = subprocess.run(cmd_blastn, capture_output=True, text=True, check=True)
        print("Finished!")
        print(result.stdout)
    except subprocess.CalledProcessError as e:
        print(f"Error during the blast search : {e.stderr}")

Blasting the transcript of interest against the P. canaliculata genome...
Finished!

In [168]:
# Check the results of this blast search
if blast_genomes == "Y":
    qresults = SearchIO.parse(blast_path, "blast-xml")

    # Generate a table of blast results grouped per probe pair # you can check the transcript ids here
    rows = []
    for qresult in qresults:
        for hit in qresult:
            for hsp in hit:
                identity = (hsp.ident_num / hsp.aln_span) * 100
                rows.append({
                    "target": hit.id,
                    "Identity": identity,
                    "Start_trans": hsp.query_start,
                    "End_trans": hsp.query_end,
                    "Start_gen": hsp.hit_start,
                    "End_gen": hsp.hit_end
                })

    df_all_hits = pd.DataFrame(rows)

In [169]:
# Extract the problematic regions in a variable
if blast_genomes == "Y":
    df_all_hits['Aln_Length'] = (df_all_hits['End_trans'] - df_all_hits['Start_trans']).abs()

    if stringent_selection == True:
        min_length_danger = math.ceil(len(fullseq) / 15)
        min_identity_danger = 80
    else:
        min_length_danger = 1
        min_identity_danger = 1

    # We define the "bad_regions" : Hits not on the transcript of interest
    mask_target = (
        (df_all_hits['target'] == best_chrom) & 
        (df_all_hits['Start_gen'] > best_start - 10) & 
        (df_all_hits['End_gen'] < best_end + 10)
    )

    df_bad_regions = df_all_hits[ (~mask_target) & (df_all_hits['Aln_Length'] >= min_length_danger) & (df_all_hits['Identity'] >= min_identity_danger) ].copy()
    df_unique = (df_bad_regions
                     .sort_values(by="Start_trans", ascending=False)
                     .drop_duplicates(subset=['Start_trans', 'End_trans']))
    print(f"\nTotal bad regions found in the transcript of interest: {len(df_unique)}")
    print("\n(Here you can check the mapping results of all the regions detected as bad in the transcript)\n")
    print(df_unique)

Total bad regions found in the transcript of interest: 0

(Here you can check the mapping results of all the regions detected as bad in the transcript)

Empty DataFrame
Columns: [target, Identity, Start_trans, End_trans, Start_gen, End_gen, Aln_Length]
Index: []

In [ ]:
# Align the remaining probes to the transcript of interest to eliminate the ones mapping in bad regions of the transcript
if blast_genomes == "Y":
    
    # Define the name of the output file
    probes_vs_trans_xml = f"output/{gene_name}_probes_against_transcript.xml"

    # Create blast command
    cmd_probes = [
        "blastn",
        "-query", fasta_path,
        "-subject", file_path,
        "-task", "blastn-short",
        "-outfmt", "5",
        "-out", probes_vs_trans_xml
    ]

    # Run blast and save the results
    try:
        print(f"Blasting the remaining probes against the transcript of interest...")
        result = subprocess.run(cmd_probes, capture_output=True, text=True, check=True)
        print("Finished!")
        print(result.stdout)
    except subprocess.CalledProcessError as e:
        print(f"Error during the blast search : {e.stderr}")

Blasting the remaining probes against the transcript of interest...
Finished!

In [171]:
# Check the results of the blast search
if blast_genomes == "Y":
    
    bad_probes = set()
    probe_hits = SearchIO.parse(probes_vs_trans_xml, "blast-xml")
    print(f"\n{'Probe':<25} | {'Alignment length':<12} | {'Identity':<8}")
    print("-" * 80)

    for qresult in probe_hits:
        probe_id = qresult.id
        for hit in qresult:
            for hsp in hit:
                p_start = hsp.hit_start
                p_end = hsp.hit_end
                p_ident = (hsp.ident_num / hsp.aln_span) * 100
                identity = (hsp.ident_num / hsp.aln_span) * 100
            
                # We check if this probe overlap with any bad region of the transcript
                for b_start, b_end in df_bad_regions[['Start_trans', 'End_trans']].itertuples(index=False):
                
                    # Intersection calculation
                    overlap = min(p_end, b_end) - max(p_start, b_start)
                
                    if overlap >= 20 and p_ident >= 90:
                        bad_probes.add(probe_id)
                        print(f"{probe_id:<25} | {overlap:>3} bases    | {p_ident:>6.2f}%")
                        break

    print("-" * 80)
    print(f"\n Number of problematic probes: {len(bad_probes)}")
    print(bad_probes)

Probe                     | Alignment length | Identity
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

 Number of problematic probes: 0
set()

In [ ]:
# Decide to remove or to keep the probes
if blast_genomes == "Y":
    
    if not bad_probes:
        df_qc_blast_2 = df_qc_blast
        print("No problematic probes were found to map in the problematic regions of the transcript of interest.")
    else:
        print(f"{len(bad_probes)} probes align in the problematic regions of the transcript of interest: {bad_probes}")
    
        choice = input("\nDo you want to remove any probes? (Y/N): ").strip().upper()
    
        if choice == "Y":
            all_question = input("\nDo you want to exclude ALL detected bad probes? (Y/N): ").strip().upper()
        
            if all_question == "Y":
                to_exclude = list(bad_probes)
            else:
                print("Current bad probes:", bad_probes)
                custom_list = input("Enter the names of the probes to exclude (separated by space): ").strip()
                to_exclude = custom_list.split()

            # DataFrame filtering
            # We suppose that the index of df_qc_blast contains the names (ex: LOC112557455_B5_PP_1)
            on_topic_indexes = [n for n, probe in enumerate(df_qc_blast.index.values) if probe not in to_exclude]
            df_qc_blast_2 = df_qc_blast.iloc[on_topic_indexes]
        
            print(f"\n{len(on_topic_indexes)} probes kept:\n", df_qc_blast_2.index.unique().values)
        
            # Update and export
            df_blast = pd.DataFrame(df_qc_blast_2.index.values, columns=["Identifier"])
            df_blast["Probe"] = df_qc_blast_2.blast.values
        
            # Save TXT
            output_txt = f"output/{gene_name}_probes_updated.txt"
            df_blast.to_csv(output_txt, sep='\t', index=False, header=False, quoting=csv.QUOTE_NONE)
        
            # Save FASTA
            probe_sequences = [SeqRecord(Seq(probe), id=str(idx)) for probe, idx in zip(df_blast.Probe.values, df_blast.Identifier.values)]
            fasta_path = f"output/{gene_name}_to_blast_against_other_genome.fasta"
        
            with open(fasta_path, "w") as output_handle:
                SeqIO.write(probe_sequences, output_handle, "fasta")
                
        else:
            print("No probes were removed.")

No problematic probes were found to map in the problematic regions of the transcript of interest.

In [175]:
# If there are more than 50 probe pairs, keep only the odd rows, otherwise cut off at the specified amount
n_probes = len(df_qc_blast_2)
print("Total number of probes: ", n_probes)

if len(df_qc_blast_2.iloc[::2]) > 25:
    df_qc_blast_2 = df_qc_blast_2.iloc[::2]
    print(f"Kept odd rows ({len(df_qc_blast_2)} probes)")

df_qc_blast_2 = df_qc_blast_2.iloc[:probepair_number_cutoff]

new_length = len(df_qc_blast_2)
n_probes = new_length
print("Number of kept probes: ", n_probes)

Total number of probes:  13
Number of kept probes:  13

In [173]:
# Generate IDT order form
current_n_probes = len(df_qc_blast_2)
data_list = []

for name, row in df_qc_blast_2.iterrows():
    name_parts = str(name).split("_")
    pool_name = "_".join(name_parts[:-2]) + f"_{current_n_probes}PP"
    
    data_list.append({
        "Pool name": pool_name,
        "Sequence": row.Initiator + row.Spacer.upper() + row.Probe
    })
    
    data_list.append({
        "Pool name": pool_name,
        "Sequence": row["Probe.1"] + row["Spacer.1"].upper() + row["Initiator.1"]
    })
df_idt = pd.DataFrame(data_list)

print(f"Generated an order of {len(df_qc_blast_2)} probe pairs ({len(df_idt)} oligos)")
print(df_idt)

Generated an order of 13 probe pairs (26 oligos)
               Pool name                                       Sequence
0   LOC112557455_B5_13PP  CTCACTCCCAATCTCTATAAGCCCTGTGTGTACCAGGAGTAGTGA
1   LOC112557455_B5_13PP  TCAGCAGCGACTGCTGGTGGGCATGAACTACCCTACAAATCCAAT
2   LOC112557455_B5_13PP  CTCACTCCCAATCTCTATAAACGACACCGGCATCATGGAGCCGCT
3   LOC112557455_B5_13PP  ACGCCGGCTGCGGACTCAGGGAGGAAACTACCCTACAAATCCAAT
4   LOC112557455_B5_13PP  CTCACTCCCAATCTCTATAATGGGGGTGCATGTCTCCCTGGGGTG
5   LOC112557455_B5_13PP  TGTTGCTGGTGGGGAGTGCCCGGCTAACTACCCTACAAATCCAAT
6   LOC112557455_B5_13PP  CTCACTCCCAATCTCTATAAGGGGCGGAGCTGGGGGCCCCTGGTG
7   LOC112557455_B5_13PP  GTCCCGGCTGTTGCTGCTGGTTTGGAACTACCCTACAAATCCAAT
8   LOC112557455_B5_13PP  CTCACTCCCAATCTCTATAAGTTGGGAGGAAGTGGAGGGTTGGAG
9   LOC112557455_B5_13PP  TGGTGGCGTGTGCTGCAGGGTCGGAAACTACCCTACAAATCCAAT
10  LOC112557455_B5_13PP  CTCACTCCCAATCTCTATAACTTCCGGGTGGGGTGCCGCCTTGCT
11  LOC112557455_B5_13PP  TGGCCCCCGGGTCCTGGCTGACCGAAACTACCCTACAAATCCAAT
12  LOC112557455_B5_13PP  CTCACTCCCAATCTCTATAATTTGAAACCATATCTTAACCTGGGT
13  LOC112557455_B5_13PP  TTATTTTCTTGTACTTGGAGCGACGAACTACCCTACAAATCCAAT
14  LOC112557455_B5_13PP  CTCACTCCCAATCTCTATAACGCGCGCTCGGGAAGAGCCAGGTAC
15  LOC112557455_B5_13PP  GGTGAGTCCGAGGGACGCCGCCAGCAACTACCCTACAAATCCAAT
16  LOC112557455_B5_13PP  CTCACTCCCAATCTCTATAATGGAGTTGGAGACTGGAGTATATGG
17  LOC112557455_B5_13PP  GTCCTCTGGAAGCGTCTGTTCAGCTAACTACCCTACAAATCCAAT
18  LOC112557455_B5_13PP  CTCACTCCCAATCTCTATAAAGTCTGGTACGGCGACATAGGAAAA
19  LOC112557455_B5_13PP  ACTTTTGTCATCTCTTGGTGGCGATAACTACCCTACAAATCCAAT
20  LOC112557455_B5_13PP  CTCACTCCCAATCTCTATAAATGGAATTCATCGCAGCAAACGGGT
21  LOC112557455_B5_13PP  GGGAGGGCATTATATCCGGGTGGGCAACTACCCTACAAATCCAAT
22  LOC112557455_B5_13PP  CTCACTCCCAATCTCTATAACAGAAAACACACTTTCGTGCTGGTG
23  LOC112557455_B5_13PP  CAAGGTGGCCCCTGCCGTGTTGGGGAACTACCCTACAAATCCAAT
24  LOC112557455_B5_13PP  CTCACTCCCAATCTCTATAAAAGGCCGACTTGCCGACCATCTCTT
25  LOC112557455_B5_13PP  GGGATCTGTTGTTGCTGCAGCTCCAAACTACCCTACAAATCCAAT

In [ ]:
# Export order form

idt_path = f"output/{gene_name}_idt_order.xlsx"

df_idt.to_excel(idt_path, index=False)