# Run Easy_HCR and check probe pair quality

This notebook is used to run Easy_HCR and then check the quality of the probe pairs (PP) generated.
In order to run this notebook you can just **click on the double arrow button** at the top left of the notebook. This will then **run automatically everything** and will **stop** at certain steps so you can **make a decision** on some parameters. In that case you never need to run a cell (grey rectangle in the code) yourself, they are executed automatically one by one.

You can also **run it step by step** if you **select the cell and click on the single arrow** on the top left of the notebook. In that case you need to **redo this for every cell of the notebook**.

For more information on Easy_HCR refer to the [website](https://gitlab.com/NCDRlab/easy_hcr)

In [1]:
import pandas as pd
import numpy as np
import csv
import subprocess
import gzip
import math
from insitu_probe_generator.maker37cb import maker
from insitu_probe_generator.start import start
from Bio import SearchIO
from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio.Blast import NCBIXML
from pathlib import Path

In [2]:
# Set the quality control parameters for the probeset
# if you do not want to remove the GC's you can set 'remove_gc' to 'False'
# if you want a more relaxed search for your blast analysis you can set 'stringent_blast_search' to 'False'

remove_gc = True
probepair_number_cutoff = 33
blast_on_genome = True

stringent_transcriptome = input("Do you want to do a stringent blast search against the transcriptome? (Y/N): \n This will make the blast search more strict to find hits in the transcriptome so you will find less problematic probes.\n The default is False but if too many probes are found I suggest to set this parameter to True.").strip().upper()
if stringent_transcriptome == "Y":
    stringent_blast_search = True
    print("\nThe transcriptome search will be stringent.\n")
else:
    stringent_blast_search = False
    print("\nThe transcriptome search will not be stringent.\n")
        
stringent_genome = input("Do you want to do a stringent blast search against the genome? (Y/N): \n This will make the blast search more strict to find hits in the transcriptome so you will find less problematic probes.\n The default is False but if too many probes are found I suggest to set this parameter to True.").strip().upper()
if stringent_genome == "Y":
    stringent_selection = True
    print("\nThe blast search against the genome will be stringent.")
else:
    stringent_selection = False
    print("\nThe blast search against the genome will not be stringent")

Do you want to do a stringent blast search against the transcriptome? (Y/N):
 This will make the blast search more strict to find hits in the transcriptome so you will find less problematic probes.
 The default is False but if too many probes are found I suggest to set this parameter to True. F

The transcriptome search will not be stringent.

Do you want to do a stringent blast search against the genome? (Y/N):
 This will make the blast search more strict to find hits in the transcriptome so you will find less problematic probes.
 The default is False but if too many probes are found I suggest to set this parameter to True. F

The blast search against the genome will not be stringent

In [3]:
# Create an output directory

Path("output").mkdir(parents=True, exist_ok=True)

In [4]:
# Run the probe generator

strt = start()
name,fullseq,amplifier,pause,choose,polyAT,polyCG,BlastProbes,db,dropout,show,report,maxprobe,numbr = strt[0],strt[1],strt[2],strt[3],strt[4],strt[5],strt[6],strt[7],strt[8],strt[9],strt[10],strt[11],strt[12],strt[13]
string_output = maker(name,fullseq,amplifier,pause,choose,polyAT,polyCG,BlastProbes,db,dropout,show,report,maxprobe,numbr)

What is the gene name? (ex. eGFP)  ENSMUST00000113438
Enter the sense sequence of your cDNA without spaces or returns.  ATGCAGTTAGTATCCTGGGCCACACTGCTAACGCTCCTGGTGCCGGACCTGGTTGAGATGAGGAGCCCTGACTCCGCGGCGGCCGTGCGCAAGGACAGGCTGCACCCGAGGCAAGTGAAATTATTAGAGAGTCTGAGCGAATATGAGATCGCGTCTCCCATCCGAGTGAACCCCCTCGGGGAACCCTTTCCCACGAACGTGCACTTCAAAAGAAGGCGGCGAAGCATTAACTCTGCCTCTGACCCCTGGCCTGCCTTCGCCTCCTCTTCGTCTTCCTCTACCTCTTCCCAGGAGCACTACCGCCTCTCAGCCTTCGGCCAGCAGTTTCTATTTAATCTCACCGCCCATACCGGATTTATCGCTCCACTGTTCACTGTCACCCTCCTTGGAGAGCCAGGGGTAAACCAGACCAAGCTGTATTCCGAGGAGGAAATGGAACTTAGGCACTGTTTCTACAAAGGCCATGTCAATACCAAGTCCGAGCACACTGCGGTCATCAGCCTGTGCTCCGGAATGATGGGCACGTTCCGCTCTCACGATGGAGATTATTTCATTGAACCACTGCAGTCTGTGGATGAGCAAGAGGATGAAGAGGAACAAAACAAACCCCACATTATTTATAGGCACAGCACCCCTCAGAGGGAACCCTCCACAGGAAAGCATGCCTGTGCCACCTCAGAACTCAAAAATAGTCACAGTAAAGACAAGCGGAAAATCAGAATGCGAAAACGGAGAAAGAGGAATAGCCTGGCTGACGACGTGGCACTGCTAAAGAGCGGTTTGGCAACAAAGGTGCTCTCTGGCTATAGCAACCAGACAAACAGCACAAGGGACAGATGGAACCACAAAAGAACCAAACGCTTTCTGTCCTACCCACGGTTTGTAGAGGTGATGGTGGTGGCTGACCACAGGATGGTTTTATACCACGGAGCAAACCTTCAACATTATATCTTAACCTTAATGTCCATTGTAGCTTCTATCTATAAAGACTCAAGTATTGGAAATTTAATTAATATTGTTATTGTGAACTTAGTTGTGATTCATAATGAACAGGAAGGACCTTACATAAATTTCAATGCCCAGACAACATTAAAGAACTTTTGCCAGTGGCAGCACTCAAAGAACTACTTGGGTGGGATTCAGCACGACACAGCCGTTCTGGTCACAAGGGAAGATATCTGCAGAGCTCAGGACAAATGTGACACCTTAGGTCTTGCTGAACTGGGAACCATTTGCGACCCCTACCGAAGCTGTTCCATTAGTGAAGACAGTGGGCTGAGCACAGCTTTCACAATAGCTCACGAGCTGGGCCATGTGTTTAATATGCCTCACGATGACAGCAATAAATGCAAAGAAGAAGGAGTTAAGAGTCCCCAGCATGTCATGGCACCAACACTGAACTTCTACACCAACCCCTGGATGTGGTCAAAGTGCAGTCGGAAATACATCACTGAGTTCCTAGACACTGGGTACGGAGAGTGCTTGCTGAATGAACCTGCATCCAGGACCTATCCTTTGCCTTCCCAACTGCCCGGCCTTCTCTACAACGTGAATAAACAATGTGAACTGATTTTTGGGCCAGGCTCTCAAGTGTGCCCCTATATGATGCAGTGCAGACGGCTCTGGTGCAATAATGTGGATGGAGCACACAAAGGCTGCAGGACTCAGCACACGCCCTGGGCAGATGGAACCGAGTGTGAGCCTGGAAAGCACTGCAAGTTTGGATTTTGTGTTCCCAAAGAAATGGAGGGCCCTGCAATTGATGGATCCTGGGGAGGTTGGAGCCACTTTGGGACCTGCTCAAGAACGTGTGGAGGAGGCATCAAAACAGCCATCAGAGAGTGCAACAGACCAGAGCCAAAAAATGGTGGGAAGTACTGTGTAGGAAGGAGAATGAAGTTCAAATCCTGCAACACGGAGCCCTGCATGAAGCAGAAGCGAGACTTCCGAGAGGAGCAGTGTGCTCACTTTGATGGCAAACACTTCAACATCAATGGTCTGCTGCCCAGCGTACGCTGGGTTCCTAAGTACAGCGGAATTTTGATGAAGGACCGGTGCAAGTTGTTCTGCAGAGTGGCAGGAAACACAGCCTACTACCAGCTCCGAGACAGAGTGATTGACGGAACCCCCTGTGGCCAGGACACAAATGACATCTGTGTCCAAGGCCTTTGCCGGCAAGCTGGATGTGATCATATTTTAAACTCAAAGGCCCGGAAAGATAAATGTGGGATTTGTGGTGGAGATAATTCTTCATGCAAAACAGTGGCAGGAACATTTAACACTGTCCATTATGGTTACAATACTGTTGTCCGAATTCCGGCTGGTGCTACCAGCATTGACGTGCGTCAGCACAGCTTCTCAGGGAAGTCTGAGGATGACAACTACCTAGCTTTATCAAACAGTAAAGGTGAATTCCTGCTAAATGGAGACTTTGTTGTCTCCATGTCCAAAAGGGAGGTCCGCGTGGGGAGCGCCGTCATTGAGTACAGCGGATCGGACAATGTGGTGGAAAGACTGAACTGTACGGACCGTATCGAGGAAGAACTTCTCCTTCAGGTGTTGTCCGTGGGAAAGCTGTATAACCCAGATGTGCGGTACTCATTCAATATTCCCATTGAGGACAAACCTCAGCAATTTTACTGGAACAGTCACGGGCCGTGGCAAGCATGCAGCAAGCCCTGCCAAGGGGAGCGGAGACGAAAACTTGTTTGCACCAGGGAGTCTGATCAGCTAACCGTTTCTGATCAAAGATGTGACCGGCTGCCCCAGCCAGGACCTGTCACTGAAGCGTGCGGCACAGACTGTGACTTGAGGTGGCACGTTGCCAGCAAGAGCGAATGCAGTGCCCAGTGTGGTTTGGGCTACCGTACTTTAGACATCCACTGTGCCAAATACAGCAGGATGGACGGGAAGACGGAGAAGGTGGATGACAGTTTCTGTAGCAGTCAACCCAGACCGAGTAACCAGGAGAAATGCTCAGGAGAGTGCAGCACAGGTGGATGGCGCTATTCAGCCTGGACCGAATGTTCTAGAAGCTGTGATGGTGGTACCCAGAGAAGAAGAGCAATTTGTGTCAACACCCGCAATGATGTCCTGGATGACAGCAAATGCACACACCAGGAGAAAGTCGTAGTACAGAGCTGCAATGAGTTCTCCTGTCCCCATTGGAAAACAGGAGACTGGTCAGAGTGCTTGGTCACCTGTGGGAAAGGGCATAAGCACCGCCAGGTCTGGTGTCAGTTTGGCGAAGATCGATTAAGCGATAGAATGTGTGACCCTGAGGCCAAGCCGGAGCCCATGCAGACGTGTCAGCAGCCAGAGTGTGCAGCTTGGCAGGCGGGTCCCTGGGGACAGTGCAGTGTCACTTGTGGACAGGGATACCAGCTAAGGGCAGTGAAGTGCATCATGGGGACTTATATGTCAGTGGTCGATGACAATGACTGTAACGCAGCAACTAGGCCAACCGACACCCAGGACTGTGAATTAGCATCTTGCCACCCTTCCATACTGGCTCTGGAACCAAGGAGAAATGCACAGAGTATACCGAGAACCCAGTGGCGATTTGGGTCTTGGACTCCATGCTCAGCCACTTGTGGAAAAGGTACCCGGATGAGATACGTCAGCTGCCGGGACGAGGACGGCTCTGTGGCTGATGAGAGTGCCTGTGCTACCTTACCTAAACCAGTAGCCAAGGAAGAGTGTTCTGTGACACCCTGTGGACAGTGGAAGGCTCTAGACTGGAGCTCTTGTTCCGTGACTTGTGGGCAAGGTAAGGCAACCCGACAAGTAGTGTGTGTCAACTACAGCGACCATGTGATTGATCGAAGTGAGTGTGACCCAGATTACATCCCCGAGACTGACCAGGACTGCTCCATGTCACCGTGCCCTCAATGGACTGGCTTGGCTCACCCATTTCAAAACGAGGACTTCCGTCCCAGGAGTGACAGCCCTAGCCGCACCCACGTGCTTGGAGGGAACCAGTGGAGAACCGGGCCCTGGGGAGCATGTTCTAGTACCTGCGCCGGAGGCTCCCAGAGGCGAGTGGTGGTGTGTCAGGATGAAAACGGATACACAGCCAATGACTGTGTAGAGAGAATCAAACCTGATGAACAGAGAGCCTGTGAATCTGGCCCGTGTCCCCAATGGGCTTACGGCAGCTGGGGAGAGTGTACCAAGCTGTGTGGTGGAGGCATGCGGACAAGACTGGTGGTCTGTCAGCGGGCCAACGGTGACCGATTCCCAGACTTGAGTTGTGAAGTCCTGGACAAACCTACTGACCGTGAGCAGTGCAACACACATGCTTGTCCACAAGATGCTGCATGGAGTACTGGCCCATGGAGCTCGTGTTCTGTCTCTTGTGGTCGAGGGCATAAACATCGAAATGTTTACTGCTTGGCAAAAGATGGAAGCCATTTAGAGAGTGATAACTGTAAGCACCTTCCTAAGCCACATGGGCACAGAAGGTGCCGAGGAGGACGGTGCCCCAGATGGAAGGCTGGCGCATGGAGTCAGTGCTCTGTGTCCTGTGGCCAAGGCGTGCAGCAGAGGCATGTGGGCTGTCAGATCGGGACACACAAAGCAGCCAGAGAGAGTGAGTGCAGCTCCTACAGCAGACCAGAGTCGGAGCGTGTCTGCCAAGCCTCACCATGTCCTCTCTACACTTGGAGGGCAGAGCAGTGGCAACAATGTACCAAGACGTGTGGCGAAGGCTCCCGGTACCGGCAGGTGGTATGCGTAGCAGAGGACCAAAGTGAGGTGCACAGCACACACTGTGACTCAGACCAGCGGCCTCCAGACCGTGAGAGCTGCAGCCTACAGCCCTGCGAGTACGTGTGGATCACAGGAGAATGGTCTGAGTGCTCAGTGACCTGTGGAAAGGGCTACAGGCAAAGGCTGGTCTCCTGCAGTGAGATTTATACCGGCAAGGAGAATTATGAATACAGCTACCAAACCACAGTGAACTGCCCAGGCGCCCAGCCGCCCAGCGTCCATCCCTGCTACTTGAGGGACTGTCCTGTCTCGGCCACCTGGAGAGTTGGCAACTGGGGCAGTTGCTCAGTGTCCTGCGGCATAGGAGTCATGCATAGATCTGTGCAGTGTTTAACTAATGAAGACCAACCCAGCCACTTATGCCCCACTGATACGAAGCCAGAAGAAAGAAAAGCCTGCCGCAATGTTTATAACTGTGAGCTACCCCAGAACTGCAAGGAGGTAAAAAAACTCAACAGCGCCAGCGTTGATGGGGAGTATTTCCTGGCTGTCAGAGGGAAGCCGCTAAAGGTATTCTGTGCAGGGATGAATTCTGACTATCCCAAGGAGTATGTGACACTGGCTCACGGTGACTCAGAGAACTTCTCCGAAGTTTATGGTCACAGATTGCACAACCCAACAGAATGTCCCTATAATGGGAGCCGGCGAGATGACTGCCATTGCCGGAAGGACTACACAGCTGCTGGCTTTTCCAGTTTCCAGAAAATCCGACTCGACCTGACCAGCATGCAGATTATAACCACTGACTTAGAGTTTGCAAGGACAAGTGAAGGACATCCTGTTCCTTTTGCCACCGCTGGGGACTGCTACAGTGCTGCCAAATGTCCACAGGGGCGCTTTAGCATCAACCTTTATGGGACTGGGCTGTCTTTAACGGAGTCTGCCAGATGGACGTCACAAGGGAATTACGCTGTTTCGGACATCAAGAAGTCTCCGGATGGTACCCGGGTCGTAGGGAAATGCGGCGGTTACTGTGGAAAGTGTACCCCATCCTCCGGCACTGGCCTGGAGGTGCGAGTTTCATAA
What is the amplifier to be used with this probe set? B1,B2,B3,B4,B5,B7,B9,B10,B11,B13,B14,B15,or B17   B1
How many bases from 5' end of the Sense RNA before starting to hybridize? ex. 100  2
What is the max acceptable length for polyA or polyT homopolymers?  5
What is the max acceptable length for polyC or polyG homopolymers?  5
Do you want to choose program options?  Y -or- N  N

HCR3.0 Probe Maker Output version 2021_0.3.2
https://doi.org/10.5281/zenodo.3871970

Written by Ryan W Null - ORCID_0000-0002-3830-4152
 with M. Desmond Ramirez - ORCID_0000-0003-3873-6999
Dennis Sun - ORCID_0000-0003-1000-7276
 and B. Duygu Ozpolat - ORCID_0000-0002-1900-965X

Copyright 2019-2021  The Ozpolat Lab,  https://bduyguozpolat.org/
 with licensing provided under GPL 3.0

For more information visit:
 https://github.com/rwnull/insitu_probe_generator





2026-10-29



From the given parameters, we were able to make 104 probe pairs.


Below is in IDT oPool submission_format.
Copy and Paste the lines below into an XLSX file for submission to IDT starting from 'Pool name'.

Pool name, Sequence
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaGCCGGAGGATGGGGTACACTTTCCA
B1_ENSMUST00000113438_104_Dla2,TTATGAAACTCGCACCTCCAGGCCAtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaGTACCATCCGGAGACTTCTTGATGT
B1_ENSMUST00000113438_104_Dla2,TAACCGCCGCATTTCCCTACGACCCtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaATCTGGCAGACTCCGTTAAAGACAG
B1_ENSMUST00000113438_104_Dla2,AAACAGCGTAATTCCCTTGTGACGTtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaCCCCTGTGGACATTTGGCAGCACTG
B1_ENSMUST00000113438_104_Dla2,AGTCCCATAAAGGTTGATGCTAAAGtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaGGATGTCCTTCACTTGTCCTTGCAA
B1_ENSMUST00000113438_104_Dla2,CAGTCCCCAGCGGTGGCAAAAGGAAtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaTGGTCAGGTCGAGTCGGATTTTCTG
B1_ENSMUST00000113438_104_Dla2,CTAAGTCAGTGGTTATAATCTGCATtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaCTTCCGGCAATGGCAGTCATCTCGC
B1_ENSMUST00000113438_104_Dla2,ACTGGAAAAGCCAGCAGCTGTGTAGtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaTTGTGCAATCTGTGACCATAAACTT
B1_ENSMUST00000113438_104_Dla2,CTCCCATTATAGGGACATTCTGTTGtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaGTGTCACATACTCCTTGGGATAGTC
B1_ENSMUST00000113438_104_Dla2,AGAAGTTCTCTGAGTCACCGTGAGCtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaCGGCTTCCCTCTGACAGCCAGGAAA
B1_ENSMUST00000113438_104_Dla2,ATTCATCCCTGCACAGAATACCTTTtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaGCTCACAGTTATAAACATTGCGGCA
B1_ENSMUST00000113438_104_Dla2,TTTTTACCTCCTTGCAGTTCTGGGGtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaGGGGCATAAGTGGCTGGGTTGGTCT
B1_ENSMUST00000113438_104_Dla2,TTTTCTTTCTTCTGGCTTCGTATCAtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaATGACTCCTATGCCGCAGGACACTG
B1_ENSMUST00000113438_104_Dla2,TTAGTTAAACACTGCACAGATCTATtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaTGGCCGAGACAGGACAGTCCCTCAA
B1_ENSMUST00000113438_104_Dla2,AACTGCCCCAGTTGCCAACTCTCCAtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaGCCTGGGCAGTTCACTGTGGTTTGG
B1_ENSMUST00000113438_104_Dla2,GCAGGGATGGACGCTGGGCGGCTGGtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaTAAATCTCACTGCAGGAGACCAGCC
B1_ENSMUST00000113438_104_Dla2,CTGTATTCATAATTCTCCTTGCCGGtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaAGCACTCAGACCATTCTCCTGTGAT
B1_ENSMUST00000113438_104_Dla2,GCCTGTAGCCCTTTCCACAGGTCACtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaGCTCTCACGGTCTGGAGGCCGCTGG
B1_ENSMUST00000113438_104_Dla2,CACGTACTCGCAGGGCTGTAGGCTGtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaCTTTGGTCCTCTGCTACGCATACCA
B1_ENSMUST00000113438_104_Dla2,GAGTCACAGTGTGTGCTGTGCACCTtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaTCTTGGTACATTGTTGCCACTGCTC
B1_ENSMUST00000113438_104_Dla2,GCCGGTACCGGGAGCCTTCGCCACAtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaGGCTTGGCAGACACGCTCCGACTCT
B1_ENSMUST00000113438_104_Dla2,CCTCCAAGTGTAGAGAGGACATGGTtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaCTGGCTGCTTTGTGTGTCCCGATCT
B1_ENSMUST00000113438_104_Dla2,CTGCTGTAGGAGCTGCACTCACTCTtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaGGCCACAGGACACAGAGCACTGACT
B1_ENSMUST00000113438_104_Dla2,AGCCCACATGCCTCTGCTGCACGCCtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaTCCTCCTCGGCACCTTCTGTGCCCA
B1_ENSMUST00000113438_104_Dla2,TGCGCCAGCCTTCCATCTGGGGCACtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaCTCTCTAAATGGCTTCCATCTTTTG
B1_ENSMUST00000113438_104_Dla2,GGCTTAGGAAGGTGCTTACAGTTATtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaCTCGACCACAAGAGACAGAACACGA
B1_ENSMUST00000113438_104_Dla2,AGCAGTAAACATTTCGATGTTTATGtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaTTGTGGACAAGCATGTGTGTTGCAC
B1_ENSMUST00000113438_104_Dla2,CCATGGGCCAGTACTCCATGCAGCAtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaTCACAACTCAAGTCTGGGAATCGGT
B1_ENSMUST00000113438_104_Dla2,TCACGGTCAGTAGGTTTGTCCAGGAtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaTTGTCCGCATGCCTCCACCACACAG
B1_ENSMUST00000113438_104_Dla2,CGTTGGCCCGCTGACAGACCACCAGtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaCCATTGGGGACACGGGCCAGATTCA
B1_ENSMUST00000113438_104_Dla2,GGTACACTCTCCCCAGCTGCCGTAAtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaTCTACACAGTCATTGGCTGTGTATC
B1_ENSMUST00000113438_104_Dla2,GCTCTCTGTTCATCAGGTTTGATTCtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaTCTGGGAGCCTCCGGCGCAGGTACT
B1_ENSMUST00000113438_104_Dla2,TTTCATCCTGACACACCACCACTCGtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaCTGGTTCCCTCCAAGCACGTGGGTG
B1_ENSMUST00000113438_104_Dla2,ACATGCTCCCCAGGGCCCGGTTCTCtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaTCCTCGTTTTGAAATGGGTGAGCCA
B1_ENSMUST00000113438_104_Dla2,CTAGGGCTGTCACTCCTGGGACGGAtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaAGCAGTCCTGGTCAGTCTCGGGGAT
B1_ENSMUST00000113438_104_Dla2,CAGTCCATTGAGGGCACGGTGACATtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaCACATGGTCGCTGTAGTTGACACAC
B1_ENSMUST00000113438_104_Dla2,ATCTGGGTCACACTCACTTCGATCAtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaCAAGTCACGGAACAAGAGCTCCAGT
B1_ENSMUST00000113438_104_Dla2,ACTTGTCGGGTTGCCTTACCTTGCCtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaCAGAACACTCTTCCTTGGCTACTGG
B1_ENSMUST00000113438_104_Dla2,GAGCCTTCCACTGTCCACAGGGTGTtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaAGCCACAGAGCCGTCCTCGTCCCGG
B1_ENSMUST00000113438_104_Dla2,AGGTAAGGTAGCACAGGCACTCTCAtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaCCACAAGTGGCTGAGCATGGAGTCC
B1_ENSMUST00000113438_104_Dla2,CTGACGTATCTCATCCGGGTACCTTtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaTACTCTGTGCATTTCTCCTTGGTTC
B1_ENSMUST00000113438_104_Dla2,ACCCAAATCGCCACTGGGTTCTCGGtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaTAATTCACAGTCCTGGGTGTCGGTT
B1_ENSMUST00000113438_104_Dla2,AGCCAGTATGGAAGGGTGGCAAGATtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaTCGACCACTGACATATAAGTCCCCA
B1_ENSMUST00000113438_104_Dla2,CTAGTTGCTGCGTTACAGTCATTGTtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaCCTGTCCACAAGTGACACTGCACTG
B1_ENSMUST00000113438_104_Dla2,TGCACTTCACTGCCCTTAGCTGGTAtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaCTCTGGCTGCTGACACGTCTGCATG
B1_ENSMUST00000113438_104_Dla2,CCAGGGACCCGCCTGCCAAGCTGCAtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaCTATCGCTTAATCGATCTTCGCCAA
B1_ENSMUST00000113438_104_Dla2,TCCGGCTTGGCCTCAGGGTCACACAtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaCTTTCCCACAGGTGACCAAGCACTC
B1_ENSMUST00000113438_104_Dla2,GACACCAGACCTGGCGGTGCTTATGtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaGGAGAACTCATTGCAGCTCTGTACT
B1_ENSMUST00000113438_104_Dla2,CCAGTCTCCTGTTTTCCAATGGGGAtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaTCATCCAGGACATCATTGCGGGTGT
B1_ENSMUST00000113438_104_Dla2,ACTTTCTCCTGGTGTGTGCATTTGCtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaCACCATCACAGCTTCTAGAACATTC
B1_ENSMUST00000113438_104_Dla2,CACAAATTGCTCTTCTTCTCTGGGTtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaGCTGCACTCTCCTGAGCATTTCTCC
B1_ENSMUST00000113438_104_Dla2,CCAGGCTGAATAGCGCCATCCACCTtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaAAACTGTCATCCACCTTCTCCGTCT
B1_ENSMUST00000113438_104_Dla2,TTACTCGGTCTGGGTTGACTGCTACtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaGGATGTCTAAAGTACGGTAGCCCAA
B1_ENSMUST00000113438_104_Dla2,CGTCCATCCTGCTGTATTTGGCACAtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaGGCAACGTGCCACCTCAAGTCACAG
B1_ENSMUST00000113438_104_Dla2,ACACTGGGCACTGCATTCGCTCTTGtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaGGCTGGGGCAGCCGGTCACATCTTT
B1_ENSMUST00000113438_104_Dla2,GTGCCGCACGCTTCAGTGACAGGTCtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaTGGTGCAAACAAGTTTTCGTCTCCG
B1_ENSMUST00000113438_104_Dla2,CAGAAACGGTTAGCTGATCAGACTCtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaCCACGGCCCGTGACTGTTCCAGTAA
B1_ENSMUST00000113438_104_Dla2,CCCTTGGCAGGGCTTGCTGCATGCTtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaTTGAATGAGTACCGCACATCTGGGT
B1_ENSMUST00000113438_104_Dla2,TGCTGAGGTTTGTCCTCAATGGGAAtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaGGAGAAGTTCTTCCTCGATACGGTC
B1_ENSMUST00000113438_104_Dla2,ACAGCTTTCCCACGGACAACACCTGtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaCGATCCGCTGTACTCAATGACGGCG
B1_ENSMUST00000113438_104_Dla2,ACAGTTCAGTCTTTCCACCACATTGtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaGAGACAACAAAGTCTCCATTTAGCA
B1_ENSMUST00000113438_104_Dla2,CCCACGCGGACCTCCCTTTTGGACAtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaGGTAGTTGTCATCCTCAGACTTCCC
B1_ENSMUST00000113438_104_Dla2,ATTCACCTTTACTGTTTGATAAAGCtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaGGTAGCACCAGCCGGAATTCGGACA
B1_ENSMUST00000113438_104_Dla2,GAAGCTGTGCTGACGCACGTCAATGtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaAATGTTCCTGCCACTGTTTTGCATG
B1_ENSMUST00000113438_104_Dla2,GTATTGTAACCATAATGGACAGTGTtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaTATCTTTCCGGGCCTTTGAGTTTAA
B1_ENSMUST00000113438_104_Dla2,AATTATCTCCACCACAAATCCCACAtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaGCCTTGGACACAGATGTCATTTGTG
B1_ENSMUST00000113438_104_Dla2,ATGATCACATCCAGCTTGCCGGCAAtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaCTGTCTCGGAGCTGGTAGTAGGCTG
B1_ENSMUST00000113438_104_Dla2,TGGCCACAGGGGGTTCCGTCAATCAtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaACCGGTCCTTCATCAAAATTCCGCT
B1_ENSMUST00000113438_104_Dla2,TTCCTGCCACTCTGCAGAACAACTTtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaCAGACCATTGATGTTGAAGTGTTTG
B1_ENSMUST00000113438_104_Dla2,CTTAGGAACCCAGCGTACGCTGGGCtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaAAGTCTCGCTTCTGCTTCATGCAGG
B1_ENSMUST00000113438_104_Dla2,TCAAAGTGAGCACACTGCTCCTCTCtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaTCCTTCCTACACAGTACTTCCCACC
B1_ENSMUST00000113438_104_Dla2,CCGTGTTGCAGGATTTGAACTTCATtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaGATGGCTGTTTTGATGCCTCCTCCA
B1_ENSMUST00000113438_104_Dla2,TTTTGGCTCTGGTCTGTTGCACTCTtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaCAACCTCCCCAGGATCCATCAATTG
B1_ENSMUST00000113438_104_Dla2,GTTCTTGAGCAGGTCCCAAAGTGGCtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaATCCAAACTTGCAGTGCTTTCCAGG
B1_ENSMUST00000113438_104_Dla2,GGCCCTCCATTTCTTTGGGAACACAtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaGTGCTGAGTCCTGCAGCCTTTGTGT
B1_ENSMUST00000113438_104_Dla2,ACACTCGGTTCCATCTGCCCAGGGCtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaCTGCACTGCATCATATAGGGGCACA
B1_ENSMUST00000113438_104_Dla2,CCATCCACATTATTGCACCAGAGCCtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaATTGTTTATTCACGTTGTAGAGAAG
B1_ENSMUST00000113438_104_Dla2,GAGAGCCTGGCCCAAAAATCAGTTCtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaCCTGGATGCAGGTTCATTCAGCAAG
B1_ENSMUST00000113438_104_Dla2,GGGCAGTTGGGAAGGCAAAGGATAGtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaGTGATGTATTTCCGACTGCACTTTG
B1_ENSMUST00000113438_104_Dla2,TCTCCGTACCCAGTGTCTAGGAACTtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaGTGTTGGTGCCATGACATGCTGGGG
B1_ENSMUST00000113438_104_Dla2,ACATCCAGGGGTTGGTGTAGAAGTTtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaGCTGTCATCGTGAGGCATATTAAAC
B1_ENSMUST00000113438_104_Dla2,CTTAACTCCTTCTTCTTTGCATTTAtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaGCTGTGCTCAGCCCACTGTCTTCAC
B1_ENSMUST00000113438_104_Dla2,TGGCCCAGCTCGTGAGCTATTGTGAtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaTGGTTCCCAGTTCAGCAAGACCTAA
B1_ENSMUST00000113438_104_Dla2,TGGAACAGCTTCGGTAGGGGTCGCAtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaATCTTCCCTTGTGACCAGAACGGCT
B1_ENSMUST00000113438_104_Dla2,GTCACATTTGTCCTGAGCTCTGCAGtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaTTTGAGTGCTGCCACTGGCAAAAGT
B1_ENSMUST00000113438_104_Dla2,TCGTGCTGAATCCCACCCAAGTAGTtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaTGTAAGGTCCTTCCTGTTCATTATG
B1_ENSMUST00000113438_104_Dla2,TTAATGTTGTCTGGGCATTGAAATTtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaAATTAAATTTCCAATACTTGAGTCT
B1_ENSMUST00000113438_104_Dla2,CACAACTAAGTTCACAATAACAATAtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaGTTAAGATATAATGTTGAAGGTTTG
B1_ENSMUST00000113438_104_Dla2,TAGATAGAAGCTACAATGGACATTAtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaCCACCACCATCACCTCTACAAACCG
B1_ENSMUST00000113438_104_Dla2,CGTGGTATAAAACCATCCTGTGGTCtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaGTGGTTCCATCTGTCCCTTGTGCTG
B1_ENSMUST00000113438_104_Dla2,GTAGGACAGAAAGCGTTTGGTTCTTtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaTTTGTTGCCAAACCGCTCTTTAGCA
B1_ENSMUST00000113438_104_Dla2,GTCTGGTTGCTATAGCCAGAGAGCAtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaTTCTCCGTTTTCGCATTCTGATTTT
B1_ENSMUST00000113438_104_Dla2,CCACGTCGTCAGCCAGGCTATTCCTtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaTTCTGAGGTGGCACAGGCATGCTTT
B1_ENSMUST00000113438_104_Dla2,CTTGTCTTTACTGTGACTATTTTTGtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaTGCCTATAAATAATGTGGGGTTTGT
B1_ENSMUST00000113438_104_Dla2,GTGGAGGGTTCCCTCTGAGGGGTGCtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaCAGACTGCAGTGGTTCAATGAAATA
B1_ENSMUST00000113438_104_Dla2,GTTCCTCTTCATCCTCTTGCTCATCtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaCATTCCGGAGCACAGGCTGATGACC
B1_ENSMUST00000113438_104_Dla2,TCCATCGTGAGAGCGGAACGTGCCCtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaCCTTTGTAGAAACAGTGCCTAAGTT
B1_ENSMUST00000113438_104_Dla2,GTGTGCTCGGACTTGGTATTGACATtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaGGTTTACCCCTGGCTCTCCAAGGAG
B1_ENSMUST00000113438_104_Dla2,TTTCCTCCTCGGAATACAGCTTGGTtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaGGTATGGGCGGTGAGATTAAATAGA
B1_ENSMUST00000113438_104_Dla2,GACAGTGAACAGTGGAGCGATAAATtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaTGCTCCTGGGAAGAGGTAGAGGAAG
B1_ENSMUST00000113438_104_Dla2,TGCTGGCCGAAGGCTGAGAGGCGGTtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaCAGAGGCAGAGTTAATGCTTCGCCG
B1_ENSMUST00000113438_104_Dla2,AAGAGGAGGCGAAGGCAGGCCAGGGtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaGGGTTCCCCGAGGGGGTTCACTCGG
B1_ENSMUST00000113438_104_Dla2,TCTTTTGAAGTGCACGTTCGTGGGAtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaCTCTCTAATAATTTCACTTGCCTCG
B1_ENSMUST00000113438_104_Dla2,GGAGACGCGATCTCATATTCGCTCAtaGAAGAGTCTTCCTTTACG
B1_ENSMUST00000113438_104_Dla2,GAGGAGGGCAGCAAACGGaaCGGAGTCAGGGCTCCTCATCTCAAC
B1_ENSMUST00000113438_104_Dla2,GCAGCCTGTCCTTGCGCACGGCCGCtaGAAGAGTCTTCCTTTACG


Figure Layout of Probe Sequences:

B1_ENSMUST00000113438_PP104_Dla2
Pair#  Initiator  Spacer  Probe  Probe  Spacer  Initiator
1   GAGGAGGGCAGCAAACGG   aa   GCCGGAGGATGGGGTACACTTTCCA     TTATGAAACTCGCACCTCCAGGCCA   ta   GAAGAGTCTTCCTTTACG
2   GAGGAGGGCAGCAAACGG   aa   GTACCATCCGGAGACTTCTTGATGT     TAACCGCCGCATTTCCCTACGACCC   ta   GAAGAGTCTTCCTTTACG
3   GAGGAGGGCAGCAAACGG   aa   ATCTGGCAGACTCCGTTAAAGACAG     AAACAGCGTAATTCCCTTGTGACGT   ta   GAAGAGTCTTCCTTTACG
4   GAGGAGGGCAGCAAACGG   aa   CCCCTGTGGACATTTGGCAGCACTG     AGTCCCATAAAGGTTGATGCTAAAG   ta   GAAGAGTCTTCCTTTACG
5   GAGGAGGGCAGCAAACGG   aa   GGATGTCCTTCACTTGTCCTTGCAA     CAGTCCCCAGCGGTGGCAAAAGGAA   ta   GAAGAGTCTTCCTTTACG
6   GAGGAGGGCAGCAAACGG   aa   TGGTCAGGTCGAGTCGGATTTTCTG     CTAAGTCAGTGGTTATAATCTGCAT   ta   GAAGAGTCTTCCTTTACG
7   GAGGAGGGCAGCAAACGG   aa   CTTCCGGCAATGGCAGTCATCTCGC     ACTGGAAAAGCCAGCAGCTGTGTAG   ta   GAAGAGTCTTCCTTTACG
8   GAGGAGGGCAGCAAACGG   aa   TTGTGCAATCTGTGACCATAAACTT     CTCCCATTATAGGGACATTCTGTTG   ta   GAAGAGTCTTCCTTTACG
9   GAGGAGGGCAGCAAACGG   aa   GTGTCACATACTCCTTGGGATAGTC     AGAAGTTCTCTGAGTCACCGTGAGC   ta   GAAGAGTCTTCCTTTACG
10   GAGGAGGGCAGCAAACGG   aa   CGGCTTCCCTCTGACAGCCAGGAAA     ATTCATCCCTGCACAGAATACCTTT   ta   GAAGAGTCTTCCTTTACG
11   GAGGAGGGCAGCAAACGG   aa   GCTCACAGTTATAAACATTGCGGCA     TTTTTACCTCCTTGCAGTTCTGGGG   ta   GAAGAGTCTTCCTTTACG
12   GAGGAGGGCAGCAAACGG   aa   GGGGCATAAGTGGCTGGGTTGGTCT     TTTTCTTTCTTCTGGCTTCGTATCA   ta   GAAGAGTCTTCCTTTACG
13   GAGGAGGGCAGCAAACGG   aa   ATGACTCCTATGCCGCAGGACACTG     TTAGTTAAACACTGCACAGATCTAT   ta   GAAGAGTCTTCCTTTACG
14   GAGGAGGGCAGCAAACGG   aa   TGGCCGAGACAGGACAGTCCCTCAA     AACTGCCCCAGTTGCCAACTCTCCA   ta   GAAGAGTCTTCCTTTACG
15   GAGGAGGGCAGCAAACGG   aa   GCCTGGGCAGTTCACTGTGGTTTGG     GCAGGGATGGACGCTGGGCGGCTGG   ta   GAAGAGTCTTCCTTTACG
16   GAGGAGGGCAGCAAACGG   aa   TAAATCTCACTGCAGGAGACCAGCC     CTGTATTCATAATTCTCCTTGCCGG   ta   GAAGAGTCTTCCTTTACG
17   GAGGAGGGCAGCAAACGG   aa   AGCACTCAGACCATTCTCCTGTGAT     GCCTGTAGCCCTTTCCACAGGTCAC   ta   GAAGAGTCTTCCTTTACG
18   GAGGAGGGCAGCAAACGG   aa   GCTCTCACGGTCTGGAGGCCGCTGG     CACGTACTCGCAGGGCTGTAGGCTG   ta   GAAGAGTCTTCCTTTACG
19   GAGGAGGGCAGCAAACGG   aa   CTTTGGTCCTCTGCTACGCATACCA     GAGTCACAGTGTGTGCTGTGCACCT   ta   GAAGAGTCTTCCTTTACG
20   GAGGAGGGCAGCAAACGG   aa   TCTTGGTACATTGTTGCCACTGCTC     GCCGGTACCGGGAGCCTTCGCCACA   ta   GAAGAGTCTTCCTTTACG
21   GAGGAGGGCAGCAAACGG   aa   GGCTTGGCAGACACGCTCCGACTCT     CCTCCAAGTGTAGAGAGGACATGGT   ta   GAAGAGTCTTCCTTTACG
22   GAGGAGGGCAGCAAACGG   aa   CTGGCTGCTTTGTGTGTCCCGATCT     CTGCTGTAGGAGCTGCACTCACTCT   ta   GAAGAGTCTTCCTTTACG
23   GAGGAGGGCAGCAAACGG   aa   GGCCACAGGACACAGAGCACTGACT     AGCCCACATGCCTCTGCTGCACGCC   ta   GAAGAGTCTTCCTTTACG
24   GAGGAGGGCAGCAAACGG   aa   TCCTCCTCGGCACCTTCTGTGCCCA     TGCGCCAGCCTTCCATCTGGGGCAC   ta   GAAGAGTCTTCCTTTACG
25   GAGGAGGGCAGCAAACGG   aa   CTCTCTAAATGGCTTCCATCTTTTG     GGCTTAGGAAGGTGCTTACAGTTAT   ta   GAAGAGTCTTCCTTTACG
26   GAGGAGGGCAGCAAACGG   aa   CTCGACCACAAGAGACAGAACACGA     AGCAGTAAACATTTCGATGTTTATG   ta   GAAGAGTCTTCCTTTACG
27   GAGGAGGGCAGCAAACGG   aa   TTGTGGACAAGCATGTGTGTTGCAC     CCATGGGCCAGTACTCCATGCAGCA   ta   GAAGAGTCTTCCTTTACG

C:\Users\enora\miniconda3\envs\HCR_new\Lib\site-packages\Bio\Application\__init__.py:39: BiopythonDeprecationWarning: The Bio.Application modules and modules relying on it have been deprecated.

Due to the on going maintenance burden of keeping command line application
wrappers up to date, we have decided to deprecate and eventually remove these
modules.

We instead now recommend building your command line and invoking it directly
with the subprocess module.
  warnings.warn(

In [5]:
gene_name = name
amplifier = amplifier

In [6]:
# Save the generated probes as CSV file

csv_path = f"output/{name}_probes.csv"

probe_file = open(csv_path, "w")
n = probe_file.write(string_output)
probe_file.close()

# Read the csv back in as table

df = pd.read_csv(
    f"output/{name}_probes.csv",
    index_col=0,
)
print("Gene: ", gene_name)
print("Amplifier: ", amplifier)
print("Probes:")
df.head()

Gene:  ENSMUST00000113438
Amplifier:  B1
Probes:

                Initiator Spacer                      Probe                    Probe.1 Spacer.1         Initiator.1
Pair#
1      GAGGAGGGCAGCAAACGG     aa  GCCGGAGGATGGGGTACACTTTCCA  TTATGAAACTCGCACCTCCAGGCCA       ta  GAAGAGTCTTCCTTTACG
2      GAGGAGGGCAGCAAACGG     aa  GTACCATCCGGAGACTTCTTGATGT  TAACCGCCGCATTTCCCTACGACCC       ta  GAAGAGTCTTCCTTTACG
3      GAGGAGGGCAGCAAACGG     aa  ATCTGGCAGACTCCGTTAAAGACAG  AAACAGCGTAATTCCCTTGTGACGT       ta  GAAGAGTCTTCCTTTACG
4      GAGGAGGGCAGCAAACGG     aa  CCCCTGTGGACATTTGGCAGCACTG  AGTCCCATAAAGGTTGATGCTAAAG       ta  GAAGAGTCTTCCTTTACG
5      GAGGAGGGCAGCAAACGG     aa  GGATGTCCTTCACTTGTCCTTGCAA  CAGTCCCCAGCGGTGGCAAAAGGAA       ta  GAAGAGTCTTCCTTTACG

In [7]:
# Generate probe identifiers

probe_identifiers = [gene_name + "_PP_" + str(n + 1) for n,_ in enumerate(df.iterrows())]
probe_identifiers = [f"{gene_name}_{amplifier}_PP_{str(n + 1)}" for n,_ in enumerate(df.iterrows())]
df.index = probe_identifiers
df.head()

                                     Initiator Spacer                      Probe                    Probe.1 Spacer.1         Initiator.1
ENSMUST00000113438_B1_PP_1  GAGGAGGGCAGCAAACGG     aa  GCCGGAGGATGGGGTACACTTTCCA  TTATGAAACTCGCACCTCCAGGCCA       ta  GAAGAGTCTTCCTTTACG
ENSMUST00000113438_B1_PP_2  GAGGAGGGCAGCAAACGG     aa  GTACCATCCGGAGACTTCTTGATGT  TAACCGCCGCATTTCCCTACGACCC       ta  GAAGAGTCTTCCTTTACG
ENSMUST00000113438_B1_PP_3  GAGGAGGGCAGCAAACGG     aa  ATCTGGCAGACTCCGTTAAAGACAG  AAACAGCGTAATTCCCTTGTGACGT       ta  GAAGAGTCTTCCTTTACG
ENSMUST00000113438_B1_PP_4  GAGGAGGGCAGCAAACGG     aa  CCCCTGTGGACATTTGGCAGCACTG  AGTCCCATAAAGGTTGATGCTAAAG       ta  GAAGAGTCTTCCTTTACG
ENSMUST00000113438_B1_PP_5  GAGGAGGGCAGCAAACGG     aa  GGATGTCCTTCACTTGTCCTTGCAA  CAGTCCCCAGCGGTGGCAAAAGGAA       ta  GAAGAGTCTTCCTTTACG

In [8]:
# Check GC-ending probes for later
# GC and the end for the forst probe and GC at the start for the second

df["GC_QC"] = df["Probe"].str.endswith("GC") | df["Probe"].str.endswith("CG") | df["Probe.1"].str.startswith("GC") | df["Probe.1"].str.startswith("CG")
print("Number of probe pairs:", len(df))
print(f"{len(df.loc[df.GC_QC == True])} GC probe pairs")
print(f"Kept {len(df.loc[df.GC_QC != True])} no-GC probe pairs")
df.head()

Number of probe pairs: 104
13 GC probe pairs
Kept 91 no-GC probe pairs

                                     Initiator Spacer                      Probe                    Probe.1 Spacer.1         Initiator.1  GC_QC
ENSMUST00000113438_B1_PP_1  GAGGAGGGCAGCAAACGG     aa  GCCGGAGGATGGGGTACACTTTCCA  TTATGAAACTCGCACCTCCAGGCCA       ta  GAAGAGTCTTCCTTTACG  False
ENSMUST00000113438_B1_PP_2  GAGGAGGGCAGCAAACGG     aa  GTACCATCCGGAGACTTCTTGATGT  TAACCGCCGCATTTCCCTACGACCC       ta  GAAGAGTCTTCCTTTACG  False
ENSMUST00000113438_B1_PP_3  GAGGAGGGCAGCAAACGG     aa  ATCTGGCAGACTCCGTTAAAGACAG  AAACAGCGTAATTCCCTTGTGACGT       ta  GAAGAGTCTTCCTTTACG  False
ENSMUST00000113438_B1_PP_4  GAGGAGGGCAGCAAACGG     aa  CCCCTGTGGACATTTGGCAGCACTG  AGTCCCATAAAGGTTGATGCTAAAG       ta  GAAGAGTCTTCCTTTACG  False
ENSMUST00000113438_B1_PP_5  GAGGAGGGCAGCAAACGG     aa  GGATGTCCTTCACTTGTCCTTGCAA  CAGTCCCCAGCGGTGGCAAAAGGAA       ta  GAAGAGTCTTCCTTTACG  False

In [9]:
# Generate BLAST sequences

df["blast"] = df["Probe"] + "NN" + df["Probe.1"]
df.head()

                                     Initiator Spacer                      Probe                    Probe.1 Spacer.1         Initiator.1  GC_QC                                              blast
ENSMUST00000113438_B1_PP_1  GAGGAGGGCAGCAAACGG     aa  GCCGGAGGATGGGGTACACTTTCCA  TTATGAAACTCGCACCTCCAGGCCA       ta  GAAGAGTCTTCCTTTACG  False  GCCGGAGGATGGGGTACACTTTCCANNTTATGAAACTCGCACCTCC...
ENSMUST00000113438_B1_PP_2  GAGGAGGGCAGCAAACGG     aa  GTACCATCCGGAGACTTCTTGATGT  TAACCGCCGCATTTCCCTACGACCC       ta  GAAGAGTCTTCCTTTACG  False  GTACCATCCGGAGACTTCTTGATGTNNTAACCGCCGCATTTCCCTA...
ENSMUST00000113438_B1_PP_3  GAGGAGGGCAGCAAACGG     aa  ATCTGGCAGACTCCGTTAAAGACAG  AAACAGCGTAATTCCCTTGTGACGT       ta  GAAGAGTCTTCCTTTACG  False  ATCTGGCAGACTCCGTTAAAGACAGNNAAACAGCGTAATTCCCTTG...
ENSMUST00000113438_B1_PP_4  GAGGAGGGCAGCAAACGG     aa  CCCCTGTGGACATTTGGCAGCACTG  AGTCCCATAAAGGTTGATGCTAAAG       ta  GAAGAGTCTTCCTTTACG  False  CCCCTGTGGACATTTGGCAGCACTGNNAGTCCCATAAAGGTTGATG...
ENSMUST00000113438_B1_PP_5  GAGGAGGGCAGCAAACGG     aa  GGATGTCCTTCACTTGTCCTTGCAA  CAGTCCCCAGCGGTGGCAAAAGGAA       ta  GAAGAGTCTTCCTTTACG  False  GGATGTCCTTCACTTGTCCTTGCAANNCAGTCCCCAGCGGTGGCAA...

In [10]:
# Create a simple dataframes for BLAST

df_blast = pd.DataFrame(df.index.values, columns=["Identifier"])
df_blast["Probe"] = df.blast.values
df_blast.to_csv(f"output/{gene_name}_probes.txt",sep='\t',index=False,header=False, quoting=csv.QUOTE_NONE)
df_blast.head()

                   Identifier                                              Probe
0  ENSMUST00000113438_B1_PP_1  GCCGGAGGATGGGGTACACTTTCCANNTTATGAAACTCGCACCTCC...
1  ENSMUST00000113438_B1_PP_2  GTACCATCCGGAGACTTCTTGATGTNNTAACCGCCGCATTTCCCTA...
2  ENSMUST00000113438_B1_PP_3  ATCTGGCAGACTCCGTTAAAGACAGNNAAACAGCGTAATTCCCTTG...
3  ENSMUST00000113438_B1_PP_4  CCCCTGTGGACATTTGGCAGCACTGNNAGTCCCATAAAGGTTGATG...
4  ENSMUST00000113438_B1_PP_5  GGATGTCCTTCACTTGTCCTTGCAANNCAGTCCCCAGCGGTGGCAA...

In [11]:
# Generate a list of SeqRecord to write a fasta file

probe_sequences = [SeqRecord(Seq(probe), id=id) for probe, id in zip(df_blast.Probe.values, df_blast.Identifier.values)]

In [12]:
# Create a fasta file containing the probe's sequences in the output folder (create this output folder in the same folder as the probe generator)

fasta_path = f"output/{gene_name}_to_blast_against_mouse_transcriptome.fasta"

with open(fasta_path, "w") as output_handle:
    for record in probe_sequences:
        SeqIO.write(record, output_handle, "fasta")

fasta_path

'output/ENSMUST00000113438_to_blast_against_mouse_transcriptome.fasta'

In [13]:
# Extract the position (chromosome, start position and end position) of the transcript of interest in the M. musculus genome.
# This step is needed for later steps

gtf_path = "necessary_files/genes.gtf.gz" # Here put the path to the annotation GTF file (make sure you have it in your Easy_HCR folder)
target_length = len(fullseq)

# The length of the transcript in the transcript FASTA file correspond to the cumulative size of each exon of a transcript in the annotation GTF file.

# We first create a dictionnary to store the cumulative size of the exons of each transcript.
transcript_data = {}

with gzip.open(gtf_path, "rt") as f:
    for line in f:
        if line.startswith("#"): continue
        columns = line.split("\t")
        
        # On ne traite que les lignes 'exon' qui contiennent le nom du gène
        if len(columns) > 8 and columns[2] == "exon" and gene_name in line:
            # Extraction de l'ID du transcrit (souvent transcript_id "ID"; dans la colonne 8)
            # On cherche l'attribut transcript_id pour grouper les exons correctement
            attributes = columns[8]
            t_id = None
            if 'transcript_id "' in attributes:
                t_id = attributes.split('transcript_id "')[1].split('"')[0]
            else:
                # Si pas de transcript_id, on utilise le gene_name comme repli
                t_id = gene_name

            exon_start = int(columns[3])
            exon_end = int(columns[4])
            exon_len = (exon_end - exon_start) + 1
            
            if t_id not in transcript_data:
                transcript_data[t_id] = {
                    "chrom": columns[0],
                    "total_len": 0,
                    "min_start": exon_start,
                    "max_end": exon_end
                }
            
            transcript_data[t_id]["total_len"] += exon_len
            # On garde les bornes génomiques min/max pour le gène
            transcript_data[t_id]["min_start"] = min(transcript_data[t_id]["min_start"], exon_start)
            transcript_data[t_id]["max_end"] = max(transcript_data[t_id]["max_end"], exon_end)

# Then, we search the transcript with the closest length to our sequence of interest.
best_chrom, best_start, best_end = None, None, None
best_t_id = None
min_diff = float('inf')

for t_id, data in transcript_data.items():
    diff = abs(data["total_len"] - target_length)
    if diff < min_diff:
        min_diff = diff
        best_t_id = t_id
        best_chrom = data["chrom"]
        best_start = data["min_start"]
        best_end = data["max_end"]

if best_chrom:
    found_len = transcript_data[best_t_id]["total_len"]
    print(f"Length of the transcript of interest: {target_length} bp")
    print(f"Best matching transcript: {best_t_id}")
    print(f"Position on M. musculus: {best_chrom}:{best_start}-{best_end}")
else:
    print(f"No exons found for '{gene_name}' in the GTF.")

Length of the transcript of interest: 5796 bp
Best matching transcript: ENSMUST00000113438
Position on M. musculus: 6:92749680-92920520

In [14]:
# Create the output path for the blast against M. musculus transcriptome
blast_path = f"output/{gene_name}_blast_against_transcriptome.xml"

In [15]:
# Create the blast command depending on the chosen mode (stringent or not)

# Define name of the transcriptome database (Don't forget to first run the custom_database_creation.ipynb script on the file)
db_path = "necessary_files/cdna_short.fa.gz"

if stringent_blast_search == True:
    cmd_blastn = [
        "blastn",
        "-query", fasta_path,
        "-db", db_path,
        "-evalue", "0.05",
        "-outfmt", "5",
        "-penalty", "-3",
        "-reward", "2",
        "-gapopen", "5",
        "-gapextend", "2",
        "-word_size", "11",
        "-out", blast_path
    ]
else:
    cmd_blastn = [
        "blastn",
        "-query", fasta_path,
        "-db", db_path,
        "-evalue", "0.2",
        "-outfmt", "5",
        "-word_size", "11",
        "-out", blast_path
    ]

In [16]:
# Run blast

try:
    print(f"Blasting the probes against the M. musculus transcriptome...")
    result = subprocess.run(cmd_blastn, capture_output=True, text=True, check=True)
    print("Finished!")
    print(result.stdout) # Print output of blast search
except subprocess.CalledProcessError as e:
    print(f"Error during the blast search : {e.stderr}")

Blasting the probes against the M. musculus transcriptome...
Finished!

In [17]:
# Read the xml file containing the results
result_handle = open(blast_path)
blast_records = list(NCBIXML.parse(result_handle))
result_handle.close()

In [18]:
# Print a table listing the blast results grouped per probe pair
# You can check the transcript ids here.

queries = []
names = []

for record in blast_records:
    for alignment in record.alignments:
        queries.append(record.query.split(" ")[0])
        title = alignment.title
        name_parts = title.split("|")
        names.append(name_parts[-1])
    

df_blast_results = pd.DataFrame(queries, columns=["Probe"])
df_blast_results["Name"] = names
df_blast_results

                            Probe                       Name
0      ENSMUST00000113438_B1_PP_1  187481 ENSMUST00000419220
1      ENSMUST00000113438_B1_PP_1  187480 ENSMUST00000419219
2      ENSMUST00000113438_B1_PP_1  187475 ENSMUST00000167391
3      ENSMUST00000113438_B1_PP_1  187474 ENSMUST00000113438
4      ENSMUST00000113438_B1_PP_2  187481 ENSMUST00000419220
5      ENSMUST00000113438_B1_PP_2  187480 ENSMUST00000419219
6      ENSMUST00000113438_B1_PP_2  187475 ENSMUST00000167391
7      ENSMUST00000113438_B1_PP_2  187474 ENSMUST00000113438
8      ENSMUST00000113438_B1_PP_3  187481 ENSMUST00000419220
9      ENSMUST00000113438_B1_PP_3  187480 ENSMUST00000419219
10     ENSMUST00000113438_B1_PP_3  187475 ENSMUST00000167391
11     ENSMUST00000113438_B1_PP_3  187474 ENSMUST00000113438
12     ENSMUST00000113438_B1_PP_4  187481 ENSMUST00000419220
13     ENSMUST00000113438_B1_PP_4  187480 ENSMUST00000419219
14     ENSMUST00000113438_B1_PP_4  187475 ENSMUST00000167391
15     ENSMUST00000113438_B1_PP_4  187474 ENSMUST00000113438
16     ENSMUST00000113438_B1_PP_4  187476 ENSMUST00000125490
17     ENSMUST00000113438_B1_PP_5  187481 ENSMUST00000419220
18     ENSMUST00000113438_B1_PP_5  187480 ENSMUST00000419219
19     ENSMUST00000113438_B1_PP_5  187476 ENSMUST00000125490
20     ENSMUST00000113438_B1_PP_5  187475 ENSMUST00000167391
21     ENSMUST00000113438_B1_PP_5  187474 ENSMUST00000113438
22     ENSMUST00000113438_B1_PP_6  187481 ENSMUST00000419220
23     ENSMUST00000113438_B1_PP_6  187480 ENSMUST00000419219
24     ENSMUST00000113438_B1_PP_6  187476 ENSMUST00000125490
25     ENSMUST00000113438_B1_PP_6  187475 ENSMUST00000167391
26     ENSMUST00000113438_B1_PP_6  187474 ENSMUST00000113438
27     ENSMUST00000113438_B1_PP_7  187481 ENSMUST00000419220
28     ENSMUST00000113438_B1_PP_7  187480 ENSMUST00000419219
29     ENSMUST00000113438_B1_PP_7  187476 ENSMUST00000125490
30     ENSMUST00000113438_B1_PP_7  187475 ENSMUST00000167391
31     ENSMUST00000113438_B1_PP_7  187474 ENSMUST00000113438
32     ENSMUST00000113438_B1_PP_8  187481 ENSMUST00000419220
33     ENSMUST00000113438_B1_PP_8  187480 ENSMUST00000419219
34     ENSMUST00000113438_B1_PP_8  187476 ENSMUST00000125490
35     ENSMUST00000113438_B1_PP_8  187475 ENSMUST00000167391
36     ENSMUST00000113438_B1_PP_8  187474 ENSMUST00000113438
37     ENSMUST00000113438_B1_PP_9  187481 ENSMUST00000419220
38     ENSMUST00000113438_B1_PP_9  187480 ENSMUST00000419219
39     ENSMUST00000113438_B1_PP_9  187476 ENSMUST00000125490
40     ENSMUST00000113438_B1_PP_9  187475 ENSMUST00000167391
41     ENSMUST00000113438_B1_PP_9  187474 ENSMUST00000113438
42    ENSMUST00000113438_B1_PP_10  187481 ENSMUST00000419220
43    ENSMUST00000113438_B1_PP_10  187480 ENSMUST00000419219
44    ENSMUST00000113438_B1_PP_10  187476 ENSMUST00000125490
45    ENSMUST00000113438_B1_PP_10  187475 ENSMUST00000167391
46    ENSMUST00000113438_B1_PP_10  187474 ENSMUST00000113438
47    ENSMUST00000113438_B1_PP_11  187481 ENSMUST00000419220
48    ENSMUST00000113438_B1_PP_11  187480 ENSMUST00000419219
49    ENSMUST00000113438_B1_PP_11  187476 ENSMUST00000125490
50    ENSMUST00000113438_B1_PP_11  187475 ENSMUST00000167391
51    ENSMUST00000113438_B1_PP_11  187474 ENSMUST00000113438
52    ENSMUST00000113438_B1_PP_12  187481 ENSMUST00000419220
53    ENSMUST00000113438_B1_PP_12  187480 ENSMUST00000419219
54    ENSMUST00000113438_B1_PP_12  187476 ENSMUST00000125490
55    ENSMUST00000113438_B1_PP_12  187475 ENSMUST00000167391
56    ENSMUST00000113438_B1_PP_12  187474 ENSMUST00000113438
57    ENSMUST00000113438_B1_PP_13  187481 ENSMUST00000419220
58    ENSMUST00000113438_B1_PP_13  187480 ENSMUST00000419219
59    ENSMUST00000113438_B1_PP_13  187476 ENSMUST00000125490
60    ENSMUST00000113438_B1_PP_13  187475 ENSMUST00000167391
61    ENSMUST00000113438_B1_PP_13  187474 ENSMUST00000113438
62    ENSMUST00000113438_B1_PP_14  187481 ENSMUST00000419220
63    ENSMUST00000113438_B1_PP_14  187480 ENSMUST00000419219
64    ENSMUST00000113438_B1_PP_14  187476 ENSMUST00000125490
65    ENSMUST00000113438_B1_PP_14  187475 ENSMUST00000167391
66    ENSMUST00000113438_B1_PP_14  187474 ENSMUST00000113438
67    ENSMUST00000113438_B1_PP_15  187481 ENSMUST00000419220
68    ENSMUST00000113438_B1_PP_15  187480 ENSMUST00000419219
69    ENSMUST00000113438_B1_PP_15  187476 ENSMUST00000125490
70    ENSMUST00000113438_B1_PP_15  187475 ENSMUST00000167391
71    ENSMUST00000113438_B1_PP_15  187474 ENSMUST00000113438
72    ENSMUST00000113438_B1_PP_16  187481 ENSMUST00000419220
73    ENSMUST00000113438_B1_PP_16  187480 ENSMUST00000419219
74    ENSMUST00000113438_B1_PP_16  187476 ENSMUST00000125490
75    ENSMUST00000113438_B1_PP_16  187475 ENSMUST00000167391
76    ENSMUST00000113438_B1_PP_16  187474 ENSMUST00000113438
77    ENSMUST00000113438_B1_PP_17  187481 ENSMUST00000419220
78    ENSMUST00000113438_B1_PP_17  187480 ENSMUST00000419219
79    ENSMUST00000113438_B1_PP_17  187476 ENSMUST00000125490
80    ENSMUST00000113438_B1_PP_17  187475 ENSMUST00000167391
81    ENSMUST00000113438_B1_PP_17  187474 ENSMUST00000113438
82    ENSMUST00000113438_B1_PP_18  187481 ENSMUST00000419220
83    ENSMUST00000113438_B1_PP_18  187480 ENSMUST00000419219
84    ENSMUST00000113438_B1_PP_18  187476 ENSMUST00000125490
85    ENSMUST00000113438_B1_PP_18  187475 ENSMUST00000167391
86    ENSMUST00000113438_B1_PP_18  187474 ENSMUST00000113438
87    ENSMUST00000113438_B1_PP_19  187481 ENSMUST00000419220
88    ENSMUST00000113438_B1_PP_19  187480 ENSMUST00000419219
89    ENSMUST00000113438_B1_PP_19  187476 ENSMUST00000125490
90    ENSMUST00000113438_B1_PP_19  187475 ENSMUST00000167391
91    ENSMUST00000113438_B1_PP_19  187474 ENSMUST00000113438
92    ENSMUST00000113438_B1_PP_20  187481 ENSMUST00000419220
93    ENSMUST00000113438_B1_PP_20  187480 ENSMUST00000419219
94    ENSMUST00000113438_B1_PP_20  187476 ENSMUST00000125490
95    ENSMUST00000113438_B1_PP_20  187475 ENSMUST00000167391
96    ENSMUST00000113438_B1_PP_20  187474 ENSMUST00000113438
97    ENSMUST00000113438_B1_PP_21  187481 ENSMUST00000419220
98    ENSMUST00000113438_B1_PP_21  187476 ENSMUST00000125490
99    ENSMUST00000113438_B1_PP_21  187475 ENSMUST00000167391
100   ENSMUST00000113438_B1_PP_21  187474 ENSMUST00000113438
101   ENSMUST00000113438_B1_PP_21  168703 ENSMUST00000300981
102   ENSMUST00000113438_B1_PP_21  168702 ENSMUST00000300980
103   ENSMUST00000113438_B1_PP_21  168701 ENSMUST00000300979
104   ENSMUST00000113438_B1_PP_21  168699 ENSMUST00000057977
105   ENSMUST00000113438_B1_PP_22  187481 ENSMUST00000419220
106   ENSMUST00000113438_B1_PP_22  187476 ENSMUST00000125490
107   ENSMUST00000113438_B1_PP_22  187475 ENSMUST00000167391
108   ENSMUST00000113438_B1_PP_22  187474 ENSMUST00000113438
109   ENSMUST00000113438_B1_PP_22  168703 ENSMUST00000300981
110   ENSMUST00000113438_B1_PP_22  168702 ENSMUST00000300980
111   ENSMUST00000113438_B1_PP_22  168701 ENSMUST00000300979
112   ENSMUST00000113438_B1_PP_22  168699 ENSMUST00000057977
113   ENSMUST00000113438_B1_PP_23  187481 ENSMUST00000419220
114   ENSMUST00000113438_B1_PP_23  187476 ENSMUST00000125490
115   ENSMUST00000113438_B1_PP_23  187475 ENSMUST00000167391
116   ENSMUST00000113438_B1_PP_23  187474 ENSMUST00000113438
117   ENSMUST00000113438_B1_PP_23  168703 ENSMUST00000300981
118   ENSMUST00000113438_B1_PP_23  168702 ENSMUST00000300980
119   ENSMUST00000113438_B1_PP_23  168701 ENSMUST00000300979
120   ENSMUST00000113438_B1_PP_23  168699 ENSMUST00000057977
121   ENSMUST00000113438_B1_PP_23  405407 ENSMUST00000488283
122   ENSMUST00000113438_B1_PP_24  187480 ENSMUST00000419219
123   ENSMUST00000113438_B1_PP_24  187476 ENSMUST00000125490
124   ENSMUST00000113438_B1_PP_24  187475 ENSMUST00000167391
125   ENSMUST00000113438_B1_PP_24  187474 ENSMUST00000113438
126   ENSMUST00000113438_B1_PP_25  187480 ENSMUST00000419219
127   ENSMUST00000113438_B1_PP_25  187476 ENSMUST00000125490
128   ENSMUST00000113438_B1_PP_25  187475 ENSMUST00000167391
129   ENSMUST00000113438_B1_PP_25  187474 ENSMUST00000113438
130   ENSMUST00000113438_B1_PP_26  187480 ENSMUST00000419219
131   ENSMUST00000113438_B1_PP_26  187476 ENSMUST00000125490
132   ENSMUST00000113438_B1_PP_26  187475 ENSMUST00000167391
133   ENSMUST00000113438_B1_PP_26  187474 ENSMUST00000113438
134   ENSMUST00000113438_B1_PP_27  187481 ENSMUST00000419220
135   ENSMUST00000113438_B1_PP_27  187480 ENSMUST00000419219
136   ENSMUST00000113438_B1_PP_27  187477 ENSMUST00000130314
137   ENSMUST00000113438_B1_PP_27  187476 ENSMUST00000125490
138   ENSMUST00000113438_B1_PP_27  187475 ENSMUST00000167391
139   ENSMUST00000113438_B1_PP_27  187474 ENSMUST00000113438
140   ENSMUST00000113438_B1_PP_28  187481 ENSMUST00000419220
141   ENSMUST00000113438_B1_PP_28  187480 ENSMUST00000419219
142   ENSMUST00000113438_B1_PP_28  187477 ENSMUST00000130314
143   ENSMUST00000113438_B1_PP_28  187476 ENSMUST00000125490
144   ENSMUST00000113438_B1_PP_28  187475 ENSMUST00000167391
145   ENSMUST00000113438_B1_PP_28  187474 ENSMUST00000113438
146   ENSMUST00000113438_B1_PP_29  187481 ENSMUST00000419220
147   ENSMUST00000113438_B1_PP_29  187480 ENSMUST00000419219
148   ENSMUST00000113438_B1_PP_29  187477 ENSMUST00000130314
149   ENSMUST00000113438_B1_PP_29  187476 ENSMUST00000125490
150   ENSMUST00000113438_B1_PP_29  187475 ENSMUST00000167391
151   ENSMUST00000113438_B1_PP_29  187474 ENSMUST00000113438
152   ENSMUST00000113438_B1_PP_30  187481 ENSMUST00000419220
153   ENSMUST00000113438_B1_PP_30  187480 ENSMUST00000419219
154   ENSMUST00000113438_B1_PP_30  187478 ENSMUST00000203690
155   ENSMUST00000113438_B1_PP_30  187477 ENSMUST00000130314
156   ENSMUST00000113438_B1_PP_30  187476 ENSMUST00000125490
157   ENSMUST00000113438_B1_PP_30  187475 ENSMUST00000167391
158   ENSMUST00000113438_B1_PP_30  187474 ENSMUST00000113438
159   ENSMUST00000113438_B1_PP_31  187481 ENSMUST00000419220
160   ENSMUST00000113438_B1_PP_31  187480 ENSMUST00000419219
161   ENSMUST00000113438_B1_PP_31  187478 ENSMUST00000203690
162   ENSMUST00000113438_B1_PP_31  187477 ENSMUST00000130314
163   ENSMUST00000113438_B1_PP_31  187476 ENSMUST00000125490
164   ENSMUST00000113438_B1_PP_31  187475 ENSMUST00000167391
165   ENSMUST00000113438_B1_PP_31  187474 ENSMUST00000113438
166   ENSMUST00000113438_B1_PP_32  187481 ENSMUST00000419220
167   ENSMUST00000113438_B1_PP_32  187480 ENSMUST00000419219
168   ENSMUST00000113438_B1_PP_32  187478 ENSMUST00000203690
169   ENSMUST00000113438_B1_PP_32  187477 ENSMUST00000130314
170   ENSMUST00000113438_B1_PP_32  187476 ENSMUST00000125490
171   ENSMUST00000113438_B1_PP_32  187475 ENSMUST00000167391
172   ENSMUST00000113438_B1_PP_32  187474 ENSMUST00000113438
173   ENSMUST00000113438_B1_PP_33  187481 ENSMUST00000419220
174   ENSMUST00000113438_B1_PP_33  187480 ENSMUST00000419219
175   ENSMUST00000113438_B1_PP_33  187477 ENSMUST00000130314
176   ENSMUST00000113438_B1_PP_33  187476 ENSMUST00000125490
177   ENSMUST00000113438_B1_PP_33  187475 ENSMUST00000167391
178   ENSMUST00000113438_B1_PP_33  187474 ENSMUST00000113438
179   ENSMUST00000113438_B1_PP_34  187481 ENSMUST00000419220
180   ENSMUST00000113438_B1_PP_34  187480 ENSMUST00000419219
181   ENSMUST00000113438_B1_PP_34  187477 ENSMUST00000130314
182   ENSMUST00000113438_B1_PP_34  187476 ENSMUST00000125490
183   ENSMUST00000113438_B1_PP_34  187475 ENSMUST00000167391
184   ENSMUST00000113438_B1_PP_34  187474 ENSMUST00000113438
185   ENSMUST00000113438_B1_PP_35  187481 ENSMUST00000419220
186   ENSMUST00000113438_B1_PP_35  187480 ENSMUST00000419219
187   ENSMUST00000113438_B1_PP_35  187477 ENSMUST00000130314
188   ENSMUST00000113438_B1_PP_35  187476 ENSMUST00000125490
189   ENSMUST00000113438_B1_PP_35  187475 ENSMUST00000167391
190   ENSMUST00000113438_B1_PP_35  187474 ENSMUST00000113438
191   ENSMUST00000113438_B1_PP_36  187481 ENSMUST00000419220
192   ENSMUST00000113438_B1_PP_36  187480 ENSMUST00000419219
193   ENSMUST00000113438_B1_PP_36  187477 ENSMUST00000130314
194   ENSMUST00000113438_B1_PP_36  187476 ENSMUST00000125490
195   ENSMUST00000113438_B1_PP_36  187475 ENSMUST00000167391
196   ENSMUST00000113438_B1_PP_36  187474 ENSMUST00000113438
197   ENSMUST00000113438_B1_PP_37  187481 ENSMUST00000419220
198   ENSMUST00000113438_B1_PP_37  187480 ENSMUST00000419219
199   ENSMUST00000113438_B1_PP_37  187477 ENSMUST00000130314
200   ENSMUST00000113438_B1_PP_37  187476 ENSMUST00000125490
201   ENSMUST00000113438_B1_PP_37  187475 ENSMUST00000167391
202   ENSMUST00000113438_B1_PP_37  187474 ENSMUST00000113438
203   ENSMUST00000113438_B1_PP_38  187481 ENSMUST00000419220
204   ENSMUST00000113438_B1_PP_38  187480 ENSMUST00000419219
205   ENSMUST00000113438_B1_PP_38  187477 ENSMUST00000130314
206   ENSMUST00000113438_B1_PP_38  187476 ENSMUST00000125490
207   ENSMUST00000113438_B1_PP_38  187475 ENSMUST00000167391
208   ENSMUST00000113438_B1_PP_38  187474 ENSMUST00000113438
209   ENSMUST00000113438_B1_PP_39  187481 ENSMUST00000419220
210   ENSMUST00000113438_B1_PP_39  187480 ENSMUST00000419219
211   ENSMUST00000113438_B1_PP_39  187477 ENSMUST00000130314
212   ENSMUST00000113438_B1_PP_39  187476 ENSMUST00000125490
213   ENSMUST00000113438_B1_PP_39  187475 ENSMUST00000167391
214   ENSMUST00000113438_B1_PP_39  187474 ENSMUST00000113438
215   ENSMUST00000113438_B1_PP_40  187481 ENSMUST00000419220
216   ENSMUST00000113438_B1_PP_40  187480 ENSMUST00000419219
217   ENSMUST00000113438_B1_PP_40  187477 ENSMUST00000130314
218   ENSMUST00000113438_B1_PP_40  187476 ENSMUST00000125490
219   ENSMUST00000113438_B1_PP_40  187475 ENSMUST00000167391
220   ENSMUST00000113438_B1_PP_40  187474 ENSMUST00000113438
221   ENSMUST00000113438_B1_PP_41  187481 ENSMUST00000419220
222   ENSMUST00000113438_B1_PP_41  187480 ENSMUST00000419219
223   ENSMUST00000113438_B1_PP_41  187477 ENSMUST00000130314
224   ENSMUST00000113438_B1_PP_41  187476 ENSMUST00000125490
225   ENSMUST00000113438_B1_PP_41  187475 ENSMUST00000167391
226   ENSMUST00000113438_B1_PP_41  187474 ENSMUST00000113438
227   ENSMUST00000113438_B1_PP_42  187481 ENSMUST00000419220
228   ENSMUST00000113438_B1_PP_42  187480 ENSMUST00000419219
229   ENSMUST00000113438_B1_PP_42  187475 ENSMUST00000167391
230   ENSMUST00000113438_B1_PP_42  187474 ENSMUST00000113438
231   ENSMUST00000113438_B1_PP_43  187481 ENSMUST00000419220
232   ENSMUST00000113438_B1_PP_43  187480 ENSMUST00000419219
233   ENSMUST00000113438_B1_PP_43  187475 ENSMUST00000167391
234   ENSMUST00000113438_B1_PP_43  187474 ENSMUST00000113438
235   ENSMUST00000113438_B1_PP_44  187481 ENSMUST00000419220
236   ENSMUST00000113438_B1_PP_44  187480 ENSMUST00000419219
237   ENSMUST00000113438_B1_PP_44  187475 ENSMUST00000167391
238   ENSMUST00000113438_B1_PP_44  187474 ENSMUST00000113438
239   ENSMUST00000113438_B1_PP_45  187481 ENSMUST00000419220
240   ENSMUST00000113438_B1_PP_45  187480 ENSMUST00000419219
241   ENSMUST00000113438_B1_PP_45  187475 ENSMUST00000167391
242   ENSMUST00000113438_B1_PP_45  187474 ENSMUST00000113438
243   ENSMUST00000113438_B1_PP_46  187481 ENSMUST00000419220
244   ENSMUST00000113438_B1_PP_46  187480 ENSMUST00000419219
245   ENSMUST00000113438_B1_PP_46  187475 ENSMUST00000167391
246   ENSMUST00000113438_B1_PP_46  187474 ENSMUST00000113438
247   ENSMUST00000113438_B1_PP_47  187481 ENSMUST00000419220
248   ENSMUST00000113438_B1_PP_47  187480 ENSMUST00000419219
249   ENSMUST00000113438_B1_PP_47  187475 ENSMUST00000167391
250   ENSMUST00000113438_B1_PP_47  187474 ENSMUST00000113438
251   ENSMUST00000113438_B1_PP_48  187481 ENSMUST00000419220
252   ENSMUST00000113438_B1_PP_48  187480 ENSMUST00000419219
253   ENSMUST00000113438_B1_PP_48  187475 ENSMUST00000167391
254   ENSMUST00000113438_B1_PP_48  187474 ENSMUST00000113438
255   ENSMUST00000113438_B1_PP_49  187481 ENSMUST00000419220
256   ENSMUST00000113438_B1_PP_49  187480 ENSMUST00000419219
257   ENSMUST00000113438_B1_PP_49  187475 ENSMUST00000167391
258   ENSMUST00000113438_B1_PP_49  187474 ENSMUST00000113438
259   ENSMUST00000113438_B1_PP_50  187481 ENSMUST00000419220
260   ENSMUST00000113438_B1_PP_50  187480 ENSMUST00000419219
261   ENSMUST00000113438_B1_PP_50  187475 ENSMUST00000167391
262   ENSMUST00000113438_B1_PP_50  187474 ENSMUST00000113438
263   ENSMUST00000113438_B1_PP_51  187481 ENSMUST00000419220
264   ENSMUST00000113438_B1_PP_51  187480 ENSMUST00000419219
265   ENSMUST00000113438_B1_PP_51  187475 ENSMUST00000167391
266   ENSMUST00000113438_B1_PP_51  187474 ENSMUST00000113438
267   ENSMUST00000113438_B1_PP_52  187481 ENSMUST00000419220
268   ENSMUST00000113438_B1_PP_52  187480 ENSMUST00000419219
269   ENSMUST00000113438_B1_PP_52  187475 ENSMUST00000167391
270   ENSMUST00000113438_B1_PP_52  187474 ENSMUST00000113438
271   ENSMUST00000113438_B1_PP_53  187481 ENSMUST00000419220
272   ENSMUST00000113438_B1_PP_53  187480 ENSMUST00000419219
273   ENSMUST00000113438_B1_PP_53  187475 ENSMUST00000167391
274   ENSMUST00000113438_B1_PP_53  187474 ENSMUST00000113438
275   ENSMUST00000113438_B1_PP_54  187481 ENSMUST00000419220
276   ENSMUST00000113438_B1_PP_54  187480 ENSMUST00000419219
277   ENSMUST00000113438_B1_PP_54  187475 ENSMUST00000167391
278   ENSMUST00000113438_B1_PP_54  187474 ENSMUST00000113438
279   ENSMUST00000113438_B1_PP_55  187481 ENSMUST00000419220
280   ENSMUST00000113438_B1_PP_55  187480 ENSMUST00000419219
281   ENSMUST00000113438_B1_PP_55  187475 ENSMUST00000167391
282   ENSMUST00000113438_B1_PP_55  187474 ENSMUST00000113438
283   ENSMUST00000113438_B1_PP_55  167227 ENSMUST00000113434
284   ENSMUST00000113438_B1_PP_56  187481 ENSMUST00000419220
285   ENSMUST00000113438_B1_PP_56  187480 ENSMUST00000419219
286   ENSMUST00000113438_B1_PP_56  187475 ENSMUST00000167391
287   ENSMUST00000113438_B1_PP_56  187474 ENSMUST00000113438
288   ENSMUST00000113438_B1_PP_56  167227 ENSMUST00000113434
289   ENSMUST00000113438_B1_PP_57  187481 ENSMUST00000419220
290   ENSMUST00000113438_B1_PP_57  187480 ENSMUST00000419219
291   ENSMUST00000113438_B1_PP_57  187475 ENSMUST00000167391
292   ENSMUST00000113438_B1_PP_57  187474 ENSMUST00000113438
293   ENSMUST00000113438_B1_PP_57  167227 ENSMUST00000113434
294   ENSMUST00000113438_B1_PP_58  187481 ENSMUST00000419220
295   ENSMUST00000113438_B1_PP_58  187480 ENSMUST00000419219
296   ENSMUST00000113438_B1_PP_58  187475 ENSMUST00000167391
297   ENSMUST00000113438_B1_PP_58  187474 ENSMUST00000113438
298   ENSMUST00000113438_B1_PP_58  167227 ENSMUST00000113434
299   ENSMUST00000113438_B1_PP_59  187481 ENSMUST00000419220
300   ENSMUST00000113438_B1_PP_59  187480 ENSMUST00000419219
301   ENSMUST00000113438_B1_PP_59  187475 ENSMUST00000167391
302   ENSMUST00000113438_B1_PP_59  187474 ENSMUST00000113438
303   ENSMUST00000113438_B1_PP_59  167227 ENSMUST00000113434
304   ENSMUST00000113438_B1_PP_60  187481 ENSMUST00000419220
305   ENSMUST00000113438_B1_PP_60  187480 ENSMUST00000419219
306   ENSMUST00000113438_B1_PP_60  187475 ENSMUST00000167391
307   ENSMUST00000113438_B1_PP_60  187474 ENSMUST00000113438
308   ENSMUST00000113438_B1_PP_60  167227 ENSMUST00000113434
309   ENSMUST00000113438_B1_PP_61  187481 ENSMUST00000419220
310   ENSMUST00000113438_B1_PP_61  187480 ENSMUST00000419219
311   ENSMUST00000113438_B1_PP_61  187475 ENSMUST00000167391
312   ENSMUST00000113438_B1_PP_61  187474 ENSMUST00000113438
313   ENSMUST00000113438_B1_PP_61  167227 ENSMUST00000113434
314   ENSMUST00000113438_B1_PP_62  187481 ENSMUST00000419220
315   ENSMUST00000113438_B1_PP_62  187480 ENSMUST00000419219
316   ENSMUST00000113438_B1_PP_62  187475 ENSMUST00000167391
317   ENSMUST00000113438_B1_PP_62  187474 ENSMUST00000113438
318   ENSMUST00000113438_B1_PP_62  167227 ENSMUST00000113434
319   ENSMUST00000113438_B1_PP_63  187481 ENSMUST00000419220
320   ENSMUST00000113438_B1_PP_63  187480 ENSMUST00000419219
321   ENSMUST00000113438_B1_PP_63  187475 ENSMUST00000167391
322   ENSMUST00000113438_B1_PP_63  187474 ENSMUST00000113438
323   ENSMUST00000113438_B1_PP_64  187481 ENSMUST00000419220
324   ENSMUST00000113438_B1_PP_64  187480 ENSMUST00000419219
325   ENSMUST00000113438_B1_PP_64  187475 ENSMUST00000167391

In [19]:
# Print a table that shows the number of hits per probe pair
df_hits = df_blast_results['Probe'].value_counts().reset_index()
df_hits.columns = ['Probe', 'n_hits']
df_hits['Probe'] = df_hits['Probe'].str.split(" ").str[0]
df_hits = df_hits.set_index('Probe')

df_hits

                              n_hits
Probe
ENSMUST00000113438_B1_PP_23        9
ENSMUST00000113438_B1_PP_21        8
ENSMUST00000113438_B1_PP_22        8
ENSMUST00000113438_B1_PP_31        7
ENSMUST00000113438_B1_PP_30        7
ENSMUST00000113438_B1_PP_32        7
ENSMUST00000113438_B1_PP_39        6
ENSMUST00000113438_B1_PP_36        6
ENSMUST00000113438_B1_PP_40        6
ENSMUST00000113438_B1_PP_34        6
ENSMUST00000113438_B1_PP_29        6
ENSMUST00000113438_B1_PP_27        6
ENSMUST00000113438_B1_PP_28        6
ENSMUST00000113438_B1_PP_35        6
ENSMUST00000113438_B1_PP_38        6
ENSMUST00000113438_B1_PP_37        6
ENSMUST00000113438_B1_PP_33        6
ENSMUST00000113438_B1_PP_41        6
ENSMUST00000113438_B1_PP_19        5
ENSMUST00000113438_B1_PP_12        5
ENSMUST00000113438_B1_PP_5         5
ENSMUST00000113438_B1_PP_6         5
ENSMUST00000113438_B1_PP_7         5
ENSMUST00000113438_B1_PP_8         5
ENSMUST00000113438_B1_PP_9         5
ENSMUST00000113438_B1_PP_11        5
ENSMUST00000113438_B1_PP_10        5
ENSMUST00000113438_B1_PP_20        5
ENSMUST00000113438_B1_PP_17        5
ENSMUST00000113438_B1_PP_18        5
ENSMUST00000113438_B1_PP_15        5
ENSMUST00000113438_B1_PP_16        5
ENSMUST00000113438_B1_PP_14        5
ENSMUST00000113438_B1_PP_13        5
ENSMUST00000113438_B1_PP_59        5
ENSMUST00000113438_B1_PP_60        5
ENSMUST00000113438_B1_PP_61        5
ENSMUST00000113438_B1_PP_56        5
ENSMUST00000113438_B1_PP_55        5
ENSMUST00000113438_B1_PP_4         5
ENSMUST00000113438_B1_PP_62        5
ENSMUST00000113438_B1_PP_57        5
ENSMUST00000113438_B1_PP_58        5
ENSMUST00000113438_B1_PP_26        4
ENSMUST00000113438_B1_PP_1         4
ENSMUST00000113438_B1_PP_3         4
ENSMUST00000113438_B1_PP_24        4
ENSMUST00000113438_B1_PP_2         4
ENSMUST00000113438_B1_PP_25        4
ENSMUST00000113438_B1_PP_47        4
ENSMUST00000113438_B1_PP_48        4
ENSMUST00000113438_B1_PP_42        4
ENSMUST00000113438_B1_PP_45        4
ENSMUST00000113438_B1_PP_46        4
ENSMUST00000113438_B1_PP_43        4
ENSMUST00000113438_B1_PP_44        4
ENSMUST00000113438_B1_PP_53        4
ENSMUST00000113438_B1_PP_54        4
ENSMUST00000113438_B1_PP_51        4
ENSMUST00000113438_B1_PP_52        4
ENSMUST00000113438_B1_PP_50        4
ENSMUST00000113438_B1_PP_49        4
ENSMUST00000113438_B1_PP_63        4
ENSMUST00000113438_B1_PP_64        4
ENSMUST00000113438_B1_PP_65        4
ENSMUST00000113438_B1_PP_66        4
ENSMUST00000113438_B1_PP_67        4
ENSMUST00000113438_B1_PP_68        4
ENSMUST00000113438_B1_PP_69        4
ENSMUST00000113438_B1_PP_70        4
ENSMUST00000113438_B1_PP_71        4
ENSMUST00000113438_B1_PP_72        4
ENSMUST00000113438_B1_PP_73        4
ENSMUST00000113438_B1_PP_74        4
ENSMUST00000113438_B1_PP_75        4
ENSMUST00000113438_B1_PP_100       4
ENSMUST00000113438_B1_PP_104       4
ENSMUST00000113438_B1_PP_103       4
ENSMUST00000113438_B1_PP_102       4
ENSMUST00000113438_B1_PP_101       4
ENSMUST00000113438_B1_PP_97        4
ENSMUST00000113438_B1_PP_98        4
ENSMUST00000113438_B1_PP_99        4
ENSMUST00000113438_B1_PP_96        4
ENSMUST00000113438_B1_PP_93        4
ENSMUST00000113438_B1_PP_94        4
ENSMUST00000113438_B1_PP_95        4
ENSMUST00000113438_B1_PP_76        3
ENSMUST00000113438_B1_PP_88        3
ENSMUST00000113438_B1_PP_87        3
ENSMUST00000113438_B1_PP_86        3
ENSMUST00000113438_B1_PP_85        3
ENSMUST00000113438_B1_PP_84        3
ENSMUST00000113438_B1_PP_83        3
ENSMUST00000113438_B1_PP_82        3
ENSMUST00000113438_B1_PP_81        3
ENSMUST00000113438_B1_PP_80        3
ENSMUST00000113438_B1_PP_79        3
ENSMUST00000113438_B1_PP_78        3
ENSMUST00000113438_B1_PP_77        3
ENSMUST00000113438_B1_PP_89        3
ENSMUST00000113438_B1_PP_90        3
ENSMUST00000113438_B1_PP_91        3
ENSMUST00000113438_B1_PP_92        3

In [20]:
## Removal of all probes with too many hits in the M. musculus transcriptome.
# You need to set the numbers to the number of transcripts your gene of interest has.

hit_threshold = int(input("How many transcripts does your gene have? (number): \n This will remove the probe pairs which have more matches than your gene of interest.\n").strip())

to_exclude = df_hits.loc[df_hits.n_hits > hit_threshold].index.values.tolist()
print("Probes to remove:")
print(to_exclude)

How many transcripts does your gene have? (number):
 This will remove the probe pairs which have more matches than your gene of interest.
 8

Probes to remove:
['ENSMUST00000113438_B1_PP_23']

In [21]:
# If you need to manually remove additional probes you can paste the name between the brackets
# This prints the list of the selected probes to be removed

manual_exclude = [
    
]

probes_to_remove = to_exclude + manual_exclude
probes_to_remove

['ENSMUST00000113438_B1_PP_23']

In [22]:
# Remove unwanted probes

on_topic_indexes = [n for n, probe in enumerate(df.index.values) if probe not in probes_to_remove]
df_qc_blast = df.iloc[on_topic_indexes]
print(f"{len(on_topic_indexes)} probes kept:\n", df_qc_blast.index.unique().values)
df_qc_blast.head(10)

103 probes kept:
 ['ENSMUST00000113438_B1_PP_1' 'ENSMUST00000113438_B1_PP_2'
 'ENSMUST00000113438_B1_PP_3' 'ENSMUST00000113438_B1_PP_4'
 'ENSMUST00000113438_B1_PP_5' 'ENSMUST00000113438_B1_PP_6'
 'ENSMUST00000113438_B1_PP_7' 'ENSMUST00000113438_B1_PP_8'
 'ENSMUST00000113438_B1_PP_9' 'ENSMUST00000113438_B1_PP_10'
 'ENSMUST00000113438_B1_PP_11' 'ENSMUST00000113438_B1_PP_12'
 'ENSMUST00000113438_B1_PP_13' 'ENSMUST00000113438_B1_PP_14'
 'ENSMUST00000113438_B1_PP_15' 'ENSMUST00000113438_B1_PP_16'
 'ENSMUST00000113438_B1_PP_17' 'ENSMUST00000113438_B1_PP_18'
 'ENSMUST00000113438_B1_PP_19' 'ENSMUST00000113438_B1_PP_20'
 'ENSMUST00000113438_B1_PP_21' 'ENSMUST00000113438_B1_PP_22'
 'ENSMUST00000113438_B1_PP_24' 'ENSMUST00000113438_B1_PP_25'
 'ENSMUST00000113438_B1_PP_26' 'ENSMUST00000113438_B1_PP_27'
 'ENSMUST00000113438_B1_PP_28' 'ENSMUST00000113438_B1_PP_29'
 'ENSMUST00000113438_B1_PP_30' 'ENSMUST00000113438_B1_PP_31'
 'ENSMUST00000113438_B1_PP_32' 'ENSMUST00000113438_B1_PP_33'
 'ENSMUST00000113438_B1_PP_34' 'ENSMUST00000113438_B1_PP_35'
 'ENSMUST00000113438_B1_PP_36' 'ENSMUST00000113438_B1_PP_37'
 'ENSMUST00000113438_B1_PP_38' 'ENSMUST00000113438_B1_PP_39'
 'ENSMUST00000113438_B1_PP_40' 'ENSMUST00000113438_B1_PP_41'
 'ENSMUST00000113438_B1_PP_42' 'ENSMUST00000113438_B1_PP_43'
 'ENSMUST00000113438_B1_PP_44' 'ENSMUST00000113438_B1_PP_45'
 'ENSMUST00000113438_B1_PP_46' 'ENSMUST00000113438_B1_PP_47'
 'ENSMUST00000113438_B1_PP_48' 'ENSMUST00000113438_B1_PP_49'
 'ENSMUST00000113438_B1_PP_50' 'ENSMUST00000113438_B1_PP_51'
 'ENSMUST00000113438_B1_PP_52' 'ENSMUST00000113438_B1_PP_53'
 'ENSMUST00000113438_B1_PP_54' 'ENSMUST00000113438_B1_PP_55'
 'ENSMUST00000113438_B1_PP_56' 'ENSMUST00000113438_B1_PP_57'
 'ENSMUST00000113438_B1_PP_58' 'ENSMUST00000113438_B1_PP_59'
 'ENSMUST00000113438_B1_PP_60' 'ENSMUST00000113438_B1_PP_61'
 'ENSMUST00000113438_B1_PP_62' 'ENSMUST00000113438_B1_PP_63'
 'ENSMUST00000113438_B1_PP_64' 'ENSMUST00000113438_B1_PP_65'
 'ENSMUST00000113438_B1_PP_66' 'ENSMUST00000113438_B1_PP_67'
 'ENSMUST00000113438_B1_PP_68' 'ENSMUST00000113438_B1_PP_69'
 'ENSMUST00000113438_B1_PP_70' 'ENSMUST00000113438_B1_PP_71'
 'ENSMUST00000113438_B1_PP_72' 'ENSMUST00000113438_B1_PP_73'
 'ENSMUST00000113438_B1_PP_74' 'ENSMUST00000113438_B1_PP_75'
 'ENSMUST00000113438_B1_PP_76' 'ENSMUST00000113438_B1_PP_77'
 'ENSMUST00000113438_B1_PP_78' 'ENSMUST00000113438_B1_PP_79'
 'ENSMUST00000113438_B1_PP_80' 'ENSMUST00000113438_B1_PP_81'
 'ENSMUST00000113438_B1_PP_82' 'ENSMUST00000113438_B1_PP_83'
 'ENSMUST00000113438_B1_PP_84' 'ENSMUST00000113438_B1_PP_85'
 'ENSMUST00000113438_B1_PP_86' 'ENSMUST00000113438_B1_PP_87'
 'ENSMUST00000113438_B1_PP_88' 'ENSMUST00000113438_B1_PP_89'
 'ENSMUST00000113438_B1_PP_90' 'ENSMUST00000113438_B1_PP_91'
 'ENSMUST00000113438_B1_PP_92' 'ENSMUST00000113438_B1_PP_93'
 'ENSMUST00000113438_B1_PP_94' 'ENSMUST00000113438_B1_PP_95'
 'ENSMUST00000113438_B1_PP_96' 'ENSMUST00000113438_B1_PP_97'
 'ENSMUST00000113438_B1_PP_98' 'ENSMUST00000113438_B1_PP_99'
 'ENSMUST00000113438_B1_PP_100' 'ENSMUST00000113438_B1_PP_101'
 'ENSMUST00000113438_B1_PP_102' 'ENSMUST00000113438_B1_PP_103'
 'ENSMUST00000113438_B1_PP_104']

                                      Initiator Spacer                      Probe                    Probe.1 Spacer.1         Initiator.1  GC_QC                                              blast
ENSMUST00000113438_B1_PP_1   GAGGAGGGCAGCAAACGG     aa  GCCGGAGGATGGGGTACACTTTCCA  TTATGAAACTCGCACCTCCAGGCCA       ta  GAAGAGTCTTCCTTTACG  False  GCCGGAGGATGGGGTACACTTTCCANNTTATGAAACTCGCACCTCC...
ENSMUST00000113438_B1_PP_2   GAGGAGGGCAGCAAACGG     aa  GTACCATCCGGAGACTTCTTGATGT  TAACCGCCGCATTTCCCTACGACCC       ta  GAAGAGTCTTCCTTTACG  False  GTACCATCCGGAGACTTCTTGATGTNNTAACCGCCGCATTTCCCTA...
ENSMUST00000113438_B1_PP_3   GAGGAGGGCAGCAAACGG     aa  ATCTGGCAGACTCCGTTAAAGACAG  AAACAGCGTAATTCCCTTGTGACGT       ta  GAAGAGTCTTCCTTTACG  False  ATCTGGCAGACTCCGTTAAAGACAGNNAAACAGCGTAATTCCCTTG...
ENSMUST00000113438_B1_PP_4   GAGGAGGGCAGCAAACGG     aa  CCCCTGTGGACATTTGGCAGCACTG  AGTCCCATAAAGGTTGATGCTAAAG       ta  GAAGAGTCTTCCTTTACG  False  CCCCTGTGGACATTTGGCAGCACTGNNAGTCCCATAAAGGTTGATG...
ENSMUST00000113438_B1_PP_5   GAGGAGGGCAGCAAACGG     aa  GGATGTCCTTCACTTGTCCTTGCAA  CAGTCCCCAGCGGTGGCAAAAGGAA       ta  GAAGAGTCTTCCTTTACG  False  GGATGTCCTTCACTTGTCCTTGCAANNCAGTCCCCAGCGGTGGCAA...
ENSMUST00000113438_B1_PP_6   GAGGAGGGCAGCAAACGG     aa  TGGTCAGGTCGAGTCGGATTTTCTG  CTAAGTCAGTGGTTATAATCTGCAT       ta  GAAGAGTCTTCCTTTACG  False  TGGTCAGGTCGAGTCGGATTTTCTGNNCTAAGTCAGTGGTTATAAT...
ENSMUST00000113438_B1_PP_7   GAGGAGGGCAGCAAACGG     aa  CTTCCGGCAATGGCAGTCATCTCGC  ACTGGAAAAGCCAGCAGCTGTGTAG       ta  GAAGAGTCTTCCTTTACG   True  CTTCCGGCAATGGCAGTCATCTCGCNNACTGGAAAAGCCAGCAGCT...
ENSMUST00000113438_B1_PP_8   GAGGAGGGCAGCAAACGG     aa  TTGTGCAATCTGTGACCATAAACTT  CTCCCATTATAGGGACATTCTGTTG       ta  GAAGAGTCTTCCTTTACG  False  TTGTGCAATCTGTGACCATAAACTTNNCTCCCATTATAGGGACATT...
ENSMUST00000113438_B1_PP_9   GAGGAGGGCAGCAAACGG     aa  GTGTCACATACTCCTTGGGATAGTC  AGAAGTTCTCTGAGTCACCGTGAGC       ta  GAAGAGTCTTCCTTTACG  False  GTGTCACATACTCCTTGGGATAGTCNNAGAAGTTCTCTGAGTCACC...
ENSMUST00000113438_B1_PP_10  GAGGAGGGCAGCAAACGG     aa  CGGCTTCCCTCTGACAGCCAGGAAA  ATTCATCCCTGCACAGAATACCTTT       ta  GAAGAGTCTTCCTTTACG  False  CGGCTTCCCTCTGACAGCCAGGAAANNATTCATCCCTGCACAGAAT...

In [23]:
# Remove probes ending in GC or CG

if remove_gc == True:
    orig_number = len(df_qc_blast)
    print("Previous number of probe pairs:", orig_number)
    df_qc_blast = df_qc_blast.loc[df_qc_blast.GC_QC != True]
    print(f"{orig_number - len(df_qc_blast)} probe pairs removed due to GC issues")
    print(f"Updated number of probe pairs:", len(df_qc_blast))
df_qc_blast.head(10)

Previous number of probe pairs: 103
13 probe pairs removed due to GC issues
Updated number of probe pairs: 90

                                      Initiator Spacer                      Probe                    Probe.1 Spacer.1         Initiator.1  GC_QC                                              blast
ENSMUST00000113438_B1_PP_1   GAGGAGGGCAGCAAACGG     aa  GCCGGAGGATGGGGTACACTTTCCA  TTATGAAACTCGCACCTCCAGGCCA       ta  GAAGAGTCTTCCTTTACG  False  GCCGGAGGATGGGGTACACTTTCCANNTTATGAAACTCGCACCTCC...
ENSMUST00000113438_B1_PP_2   GAGGAGGGCAGCAAACGG     aa  GTACCATCCGGAGACTTCTTGATGT  TAACCGCCGCATTTCCCTACGACCC       ta  GAAGAGTCTTCCTTTACG  False  GTACCATCCGGAGACTTCTTGATGTNNTAACCGCCGCATTTCCCTA...
ENSMUST00000113438_B1_PP_3   GAGGAGGGCAGCAAACGG     aa  ATCTGGCAGACTCCGTTAAAGACAG  AAACAGCGTAATTCCCTTGTGACGT       ta  GAAGAGTCTTCCTTTACG  False  ATCTGGCAGACTCCGTTAAAGACAGNNAAACAGCGTAATTCCCTTG...
ENSMUST00000113438_B1_PP_4   GAGGAGGGCAGCAAACGG     aa  CCCCTGTGGACATTTGGCAGCACTG  AGTCCCATAAAGGTTGATGCTAAAG       ta  GAAGAGTCTTCCTTTACG  False  CCCCTGTGGACATTTGGCAGCACTGNNAGTCCCATAAAGGTTGATG...
ENSMUST00000113438_B1_PP_5   GAGGAGGGCAGCAAACGG     aa  GGATGTCCTTCACTTGTCCTTGCAA  CAGTCCCCAGCGGTGGCAAAAGGAA       ta  GAAGAGTCTTCCTTTACG  False  GGATGTCCTTCACTTGTCCTTGCAANNCAGTCCCCAGCGGTGGCAA...
ENSMUST00000113438_B1_PP_6   GAGGAGGGCAGCAAACGG     aa  TGGTCAGGTCGAGTCGGATTTTCTG  CTAAGTCAGTGGTTATAATCTGCAT       ta  GAAGAGTCTTCCTTTACG  False  TGGTCAGGTCGAGTCGGATTTTCTGNNCTAAGTCAGTGGTTATAAT...
ENSMUST00000113438_B1_PP_8   GAGGAGGGCAGCAAACGG     aa  TTGTGCAATCTGTGACCATAAACTT  CTCCCATTATAGGGACATTCTGTTG       ta  GAAGAGTCTTCCTTTACG  False  TTGTGCAATCTGTGACCATAAACTTNNCTCCCATTATAGGGACATT...
ENSMUST00000113438_B1_PP_9   GAGGAGGGCAGCAAACGG     aa  GTGTCACATACTCCTTGGGATAGTC  AGAAGTTCTCTGAGTCACCGTGAGC       ta  GAAGAGTCTTCCTTTACG  False  GTGTCACATACTCCTTGGGATAGTCNNAGAAGTTCTCTGAGTCACC...
ENSMUST00000113438_B1_PP_10  GAGGAGGGCAGCAAACGG     aa  CGGCTTCCCTCTGACAGCCAGGAAA  ATTCATCCCTGCACAGAATACCTTT       ta  GAAGAGTCTTCCTTTACG  False  CGGCTTCCCTCTGACAGCCAGGAAANNATTCATCCCTGCACAGAAT...
ENSMUST00000113438_B1_PP_11  GAGGAGGGCAGCAAACGG     aa  GCTCACAGTTATAAACATTGCGGCA  TTTTTACCTCCTTGCAGTTCTGGGG       ta  GAAGAGTCTTCCTTTACG  False  GCTCACAGTTATAAACATTGCGGCANNTTTTTACCTCCTTGCAGTT...

In [24]:
# Determine if you want to blast the remaining probes against the genomes of M. musculus

blast_genomes = input("Do you want to blast the remaining probes against the genomes of M. musculus? (Y/N): \nThis will blast the transcript of interest against the genomes to see which regions are problematic\nand then it will blast the remaining probes against the transcript of interest to see which probes align\nin the problematic regions of the transcript.\n").strip().upper()

Do you want to blast the remaining probes against the genomes of M. musculus? (Y/N):
This will blast the transcript of interest against the genomes to see which regions are problematic
and then it will blast the remaining probes against the transcript of interest to see which probes align
in the problematic regions of the transcript.
 Y

In [25]:
# Create a new fasta file containing the sequences of the remaining probes in the output folder
if blast_genomes == "Y":
    df_blast = pd.DataFrame(df_qc_blast.index.values, columns=["Identifier"])
    df_blast["Probe"] = df_qc_blast.blast.values
    df_blast.to_csv(f"output/{gene_name}_probes.txt",sep='\t',index=False,header=False, quoting=csv.QUOTE_NONE)
    probe_sequences = [SeqRecord(Seq(probe), id=id) for probe, id in zip(df_blast.Probe.values, df_blast.Identifier.values)]
    fasta_path = f"output/{gene_name}_to_blast_against_mouse_genome.fasta"
    with open(fasta_path, "w") as output_handle:
        for record in probe_sequences:
            SeqIO.write(record, output_handle, "fasta")

In [26]:
# Create a fasta file containing the transcript sequence in order to blast it against the M. musculus genome
if blast_genomes == "Y":
    file_path = f"output/{gene_name}.fasta"
    with open(file_path, "w") as f:
        f.write(f">{gene_name}\n")
        f.write(f"{fullseq}\n")

In [27]:
# Align the transcript of interest to the M. musculus genome for extra check
# Load database generated from M. musculus genome (Here again you need to make sure you ran the custom_database_creation.ipynb script on the file)
if blast_genomes == "Y":
    db_path = "necessary_files/GCF_000001635.27_GRCm39_genomic.fna.gz"

    # Define output file name
    blast_path = f"output/{gene_name}_blast_against_Mmus_genome.xml"

    # Create blast command
    cmd_blastn = [
        "blastn",
        "-query", file_path,
        "-db", db_path,
        "-task", "blastn",
        "-outfmt", "5",
        "-evalue", "0.05",
        "-out", blast_path
    ]

    # Run blast and save the results
    try:
        print(f"Blasting the transcript of interest against the M. musculus genome...")
        result = subprocess.run(cmd_blastn, capture_output=True, text=True, check=True)
        print("Finished!")
        print(result.stdout)
    except subprocess.CalledProcessError as e:
        print(f"Error during the blast search : {e.stderr}")

Blasting the transcript of interest against the M. musculus genome...
Finished!

In [28]:
# Check the results of this blast search
if blast_genomes == "Y":
    qresults = SearchIO.parse(blast_path, "blast-xml")

    # Generate a table of blast results grouped per probe pair # you can check the transcript ids here
    rows = []
    for qresult in qresults:
        for hit in qresult:
            for hsp in hit:
                identity = (hsp.ident_num / hsp.aln_span) * 100
                rows.append({
                    "target": hit.id,
                    "Identity": identity,
                    "Start_trans": hsp.query_start,
                    "End_trans": hsp.query_end,
                    "Start_gen": hsp.hit_start,
                    "End_gen": hsp.hit_end
                })

    df_all_hits = pd.DataFrame(rows)

In [29]:
# Extract the problematic regions in a variable
if blast_genomes == "Y":
    df_all_hits['Aln_Length'] = (df_all_hits['End_trans'] - df_all_hits['Start_trans']).abs()

    if stringent_selection == True:
        min_length_danger = math.ceil(len(fullseq) / 15)
        min_identity_danger = 80
    else:
        min_length_danger = 1
        min_identity_danger = 1

    # We define the "bad_regions" : Hits not on the transcript of interest
    mask_target = (
        (df_all_hits['target'] == best_chrom) & 
        (df_all_hits['Start_gen'] > best_start - 10) & 
        (df_all_hits['End_gen'] < best_end + 10)
    )

    df_bad_regions = df_all_hits[ (~mask_target) & (df_all_hits['Aln_Length'] >= min_length_danger) & (df_all_hits['Identity'] >= min_identity_danger) ].copy()
    df_unique = (df_bad_regions
                     .sort_values(by="Start_trans", ascending=False)
                     .drop_duplicates(subset=['Start_trans', 'End_trans']))
    print(f"\nTotal bad regions found in the transcript of interest: {len(df_unique)}")
    print("\n(Here you can check the mapping results of all the regions detected as bad in the transcript)\n")
    print(df_unique)

Total bad regions found in the transcript of interest: 15

(Here you can check the mapping results of all the regions detected as bad in the transcript)

   target   Identity  Start_trans  End_trans  Start_gen   End_gen  Aln_Length
44     15  88.461538         5550       5602   94177874  94177926          52
47     15  84.444444         4509       4554   94184322  94184367          45
46     15  70.000000         2551       2687   94236287  94236423         136
50      9  68.666667         2292       2442   30813931  30814081         150
48     15  71.578947         2292       2387   94238934  94239029          95
45     15  76.470588         2090       2175   94243557  94243642          85
42     15  70.879121         1856       2036   94243794  94243974         180
54     16  73.643411         1759       1886   85594944  85595071         127
49      9  73.451327         1197       1310   30822975  30823088         113
43     15  78.823529          969       1054   94260398  94260483          85
51      9  93.939394          255        288   45670471  45670504          33
73     10  87.179487          250        289   75832617  75832656          39
39      6  81.355932          230        288   86308890  86308948          58
41      6  81.034483          230        287   86860422  86860479          57
82      4  82.142857          230        285   52601231  52601286          55

In [30]:
# Align the remaining probes to the transcript of interest to eliminate the ones mapping in bad regions of the transcript
if blast_genomes == "Y":
    
    # Define the name of the output file
    probes_vs_trans_xml = f"output/{gene_name}_probes_against_transcript.xml"

    # Create blast command
    cmd_probes = [
        "blastn",
        "-query", fasta_path,
        "-subject", file_path,
        "-task", "blastn-short",
        "-outfmt", "5",
        "-out", probes_vs_trans_xml
    ]

    # Run blast and save the results
    try:
        print(f"Blasting the remaining probes against the transcript of interest...")
        result = subprocess.run(cmd_probes, capture_output=True, text=True, check=True)
        print("Finished!")
        print(result.stdout)
    except subprocess.CalledProcessError as e:
        print(f"Error during the blast search : {e.stderr}")

Blasting the remaining probes against the transcript of interest...
Finished!

In [31]:
# Check the results of the blast search
if blast_genomes == "Y":
    
    bad_probes = set()
    probe_hits = SearchIO.parse(probes_vs_trans_xml, "blast-xml")
    print(f"\n{'Probe':<25} | {'Alignment length':<12} | {'Identity':<8}")
    print("-" * 80)

    for qresult in probe_hits:
        probe_id = qresult.id
        for hit in qresult:
            for hsp in hit:
                p_start = hsp.hit_start
                p_end = hsp.hit_end
                p_ident = (hsp.ident_num / hsp.aln_span) * 100
                identity = (hsp.ident_num / hsp.aln_span) * 100
            
                # We check if this probe overlap with any bad region of the transcript
                for b_start, b_end in df_bad_regions[['Start_trans', 'End_trans']].itertuples(index=False):
                
                    # Intersection calculation
                    overlap = min(p_end, b_end) - max(p_start, b_start)
                
                    if overlap >= 20 and p_ident >= 90:
                        bad_probes.add(probe_id)
                        print(f"{probe_id:<25} | {overlap:>3} bases    | {p_ident:>6.2f}%")
                        break

    print("-" * 80)
    print(f"\n Number of problematic probes: {len(bad_probes)}")
    print(bad_probes)

Probe                     | Alignment length | Identity
--------------------------------------------------------------------------------
ENSMUST00000113438_B1_PP_4 |  23 bases    | 100.00%
ENSMUST00000113438_B1_PP_5 |  25 bases    | 100.00%
ENSMUST00000113438_B1_PP_57 |  25 bases    | 100.00%
ENSMUST00000113438_B1_PP_57 |  24 bases    | 100.00%
ENSMUST00000113438_B1_PP_58 |  25 bases    | 100.00%
ENSMUST00000113438_B1_PP_58 |  25 bases    | 100.00%
ENSMUST00000113438_B1_PP_59 |  25 bases    | 100.00%
ENSMUST00000113438_B1_PP_61 |  25 bases    | 100.00%
ENSMUST00000113438_B1_PP_62 |  25 bases    | 100.00%
ENSMUST00000113438_B1_PP_62 |  25 bases    | 100.00%
ENSMUST00000113438_B1_PP_63 |  25 bases    | 100.00%
ENSMUST00000113438_B1_PP_63 |  25 bases    | 100.00%
ENSMUST00000113438_B1_PP_66 |  25 bases    | 100.00%
ENSMUST00000113438_B1_PP_67 |  21 bases    | 100.00%
ENSMUST00000113438_B1_PP_67 |  25 bases    | 100.00%
ENSMUST00000113438_B1_PP_69 |  25 bases    | 100.00%
ENSMUST00000113438_B1_PP_69 |  25 bases    | 100.00%
ENSMUST00000113438_B1_PP_70 |  25 bases    | 100.00%
ENSMUST00000113438_B1_PP_70 |  25 bases    | 100.00%
ENSMUST00000113438_B1_PP_71 |  25 bases    | 100.00%
ENSMUST00000113438_B1_PP_71 |  25 bases    | 100.00%
ENSMUST00000113438_B1_PP_72 |  25 bases    | 100.00%
ENSMUST00000113438_B1_PP_72 |  25 bases    | 100.00%
ENSMUST00000113438_B1_PP_73 |  22 bases    | 100.00%
ENSMUST00000113438_B1_PP_73 |  25 bases    | 100.00%
ENSMUST00000113438_B1_PP_82 |  25 bases    | 100.00%
ENSMUST00000113438_B1_PP_82 |  22 bases    | 100.00%
ENSMUST00000113438_B1_PP_83 |  25 bases    | 100.00%
ENSMUST00000113438_B1_PP_83 |  25 bases    | 100.00%
ENSMUST00000113438_B1_PP_87 |  25 bases    | 100.00%
ENSMUST00000113438_B1_PP_87 |  25 bases    | 100.00%
--------------------------------------------------------------------------------

 Number of problematic probes: 18
{'ENSMUST00000113438_B1_PP_58', 'ENSMUST00000113438_B1_PP_59', 'ENSMUST00000113438_B1_PP_66', 'ENSMUST00000113438_B1_PP_63', 'ENSMUST00000113438_B1_PP_70', 'ENSMUST00000113438_B1_PP_72', 'ENSMUST00000113438_B1_PP_73', 'ENSMUST00000113438_B1_PP_83', 'ENSMUST00000113438_B1_PP_62', 'ENSMUST00000113438_B1_PP_61', 'ENSMUST00000113438_B1_PP_87', 'ENSMUST00000113438_B1_PP_67', 'ENSMUST00000113438_B1_PP_5', 'ENSMUST00000113438_B1_PP_57', 'ENSMUST00000113438_B1_PP_71', 'ENSMUST00000113438_B1_PP_82', 'ENSMUST00000113438_B1_PP_69', 'ENSMUST00000113438_B1_PP_4'}

In [32]:
# Decide to remove or to keep the probes
if blast_genomes == "Y":
    
    if not bad_probes:
        df_qc_blast_2 = df_qc_blast
        print("No problematic probes were found to map in the problematic regions of the transcript of interest.")
    else:
        print(f"{len(bad_probes)} probes align in the problematic regions of the transcript of interest: {bad_probes}")
    
        choice = input("\nDo you want to remove any probes? (Y/N): ").strip().upper()
    
        if choice == "Y":
            all_question = input("\nDo you want to exclude ALL detected bad probes? (Y/N): ").strip().upper()
        
            if all_question == "Y":
                to_exclude = list(bad_probes)
            else:
                print("Current bad probes:", bad_probes)
                custom_list = input("Enter the names of the probes to exclude (separated by space): ").strip()
                to_exclude = custom_list.split()

            # DataFrame filtering
            # We suppose that the index of df_qc_blast contains the names (ex: LOC112557455_B5_PP_1)
            on_topic_indexes = [n for n, probe in enumerate(df_qc_blast.index.values) if probe not in to_exclude]
            df_qc_blast_2 = df_qc_blast.iloc[on_topic_indexes]
        
            print(f"\n{len(on_topic_indexes)} probes kept:\n", df_qc_blast_2.index.unique().values)
        
            # Update and export
            df_blast = pd.DataFrame(df_qc_blast_2.index.values, columns=["Identifier"])
            df_blast["Probe"] = df_qc_blast_2.blast.values
        
            # Save TXT
            output_txt = f"output/{gene_name}_probes_updated.txt"
            df_blast.to_csv(output_txt, sep='\t', index=False, header=False, quoting=csv.QUOTE_NONE)
        
            # Save FASTA
            probe_sequences = [SeqRecord(Seq(probe), id=str(idx)) for probe, idx in zip(df_blast.Probe.values, df_blast.Identifier.values)]
            fasta_path = f"output/{gene_name}_to_blast_against_other_genome.fasta"
        
            with open(fasta_path, "w") as output_handle:
                SeqIO.write(probe_sequences, output_handle, "fasta")
                
        else:
            print("No probes were removed.")

18 probes align in the problematic regions of the transcript of interest: {'ENSMUST00000113438_B1_PP_58', 'ENSMUST00000113438_B1_PP_59', 'ENSMUST00000113438_B1_PP_66', 'ENSMUST00000113438_B1_PP_63', 'ENSMUST00000113438_B1_PP_70', 'ENSMUST00000113438_B1_PP_72', 'ENSMUST00000113438_B1_PP_73', 'ENSMUST00000113438_B1_PP_83', 'ENSMUST00000113438_B1_PP_62', 'ENSMUST00000113438_B1_PP_61', 'ENSMUST00000113438_B1_PP_87', 'ENSMUST00000113438_B1_PP_67', 'ENSMUST00000113438_B1_PP_5', 'ENSMUST00000113438_B1_PP_57', 'ENSMUST00000113438_B1_PP_71', 'ENSMUST00000113438_B1_PP_82', 'ENSMUST00000113438_B1_PP_69', 'ENSMUST00000113438_B1_PP_4'}

Do you want to remove any probes? (Y/N):  Y

Do you want to exclude ALL detected bad probes? (Y/N):  Y

72 probes kept:
 ['ENSMUST00000113438_B1_PP_1' 'ENSMUST00000113438_B1_PP_2'
 'ENSMUST00000113438_B1_PP_3' 'ENSMUST00000113438_B1_PP_6'
 'ENSMUST00000113438_B1_PP_8' 'ENSMUST00000113438_B1_PP_9'
 'ENSMUST00000113438_B1_PP_10' 'ENSMUST00000113438_B1_PP_11'
 'ENSMUST00000113438_B1_PP_12' 'ENSMUST00000113438_B1_PP_13'
 'ENSMUST00000113438_B1_PP_14' 'ENSMUST00000113438_B1_PP_16'
 'ENSMUST00000113438_B1_PP_18' 'ENSMUST00000113438_B1_PP_19'
 'ENSMUST00000113438_B1_PP_21' 'ENSMUST00000113438_B1_PP_22'
 'ENSMUST00000113438_B1_PP_24' 'ENSMUST00000113438_B1_PP_25'
 'ENSMUST00000113438_B1_PP_26' 'ENSMUST00000113438_B1_PP_27'
 'ENSMUST00000113438_B1_PP_28' 'ENSMUST00000113438_B1_PP_30'
 'ENSMUST00000113438_B1_PP_32' 'ENSMUST00000113438_B1_PP_33'
 'ENSMUST00000113438_B1_PP_34' 'ENSMUST00000113438_B1_PP_35'
 'ENSMUST00000113438_B1_PP_36' 'ENSMUST00000113438_B1_PP_37'
 'ENSMUST00000113438_B1_PP_38' 'ENSMUST00000113438_B1_PP_39'
 'ENSMUST00000113438_B1_PP_40' 'ENSMUST00000113438_B1_PP_41'
 'ENSMUST00000113438_B1_PP_42' 'ENSMUST00000113438_B1_PP_43'
 'ENSMUST00000113438_B1_PP_44' 'ENSMUST00000113438_B1_PP_45'
 'ENSMUST00000113438_B1_PP_46' 'ENSMUST00000113438_B1_PP_47'
 'ENSMUST00000113438_B1_PP_48' 'ENSMUST00000113438_B1_PP_49'
 'ENSMUST00000113438_B1_PP_50' 'ENSMUST00000113438_B1_PP_51'
 'ENSMUST00000113438_B1_PP_52' 'ENSMUST00000113438_B1_PP_54'
 'ENSMUST00000113438_B1_PP_55' 'ENSMUST00000113438_B1_PP_64'
 'ENSMUST00000113438_B1_PP_65' 'ENSMUST00000113438_B1_PP_68'
 'ENSMUST00000113438_B1_PP_74' 'ENSMUST00000113438_B1_PP_75'
 'ENSMUST00000113438_B1_PP_76' 'ENSMUST00000113438_B1_PP_77'
 'ENSMUST00000113438_B1_PP_78' 'ENSMUST00000113438_B1_PP_79'
 'ENSMUST00000113438_B1_PP_80' 'ENSMUST00000113438_B1_PP_81'
 'ENSMUST00000113438_B1_PP_84' 'ENSMUST00000113438_B1_PP_85'
 'ENSMUST00000113438_B1_PP_86' 'ENSMUST00000113438_B1_PP_88'
 'ENSMUST00000113438_B1_PP_90' 'ENSMUST00000113438_B1_PP_91'
 'ENSMUST00000113438_B1_PP_92' 'ENSMUST00000113438_B1_PP_93'
 'ENSMUST00000113438_B1_PP_94' 'ENSMUST00000113438_B1_PP_95'
 'ENSMUST00000113438_B1_PP_96' 'ENSMUST00000113438_B1_PP_97'
 'ENSMUST00000113438_B1_PP_98' 'ENSMUST00000113438_B1_PP_99'
 'ENSMUST00000113438_B1_PP_100' 'ENSMUST00000113438_B1_PP_102']

In [33]:
# If there are more than 50 probe pairs, keep only the odd rows, otherwise cut off at the specified amount
n_probes = len(df_qc_blast_2)
print("Total number of probes: ", n_probes)

if len(df_qc_blast_2.iloc[::2]) > 25:
    df_qc_blast_2 = df_qc_blast_2.iloc[::2]
    print(f"Kept odd rows ({len(df_qc_blast_2)} probes)")

df_qc_blast_2 = df_qc_blast_2.iloc[:probepair_number_cutoff]

new_length = len(df_qc_blast_2)
n_probes = new_length
print("Number of kept probes: ", n_probes)

Total number of probes:  72
Kept odd rows (36 probes)
Number of kept probes:  33

In [34]:
# Generate IDT order form
current_n_probes = len(df_qc_blast_2)
data_list = []

for name, row in df_qc_blast_2.iterrows():
    name_parts = str(name).split("_")
    pool_name = "_".join(name_parts[:-2]) + f"_{current_n_probes}PP"
    
    data_list.append({
        "Pool name": pool_name,
        "Sequence": row.Initiator + row.Spacer.upper() + row.Probe
    })
    
    data_list.append({
        "Pool name": pool_name,
        "Sequence": row["Probe.1"] + row["Spacer.1"].upper() + row["Initiator.1"]
    })
df_idt = pd.DataFrame(data_list)

print(f"Generated an order of {len(df_qc_blast_2)} probe pairs ({len(df_idt)} oligos)")
print(df_idt)

Generated an order of 33 probe pairs (66 oligos)
                     Pool name                                       Sequence
0   ENSMUST00000113438_B1_33PP  GAGGAGGGCAGCAAACGGAAGCCGGAGGATGGGGTACACTTTCCA
1   ENSMUST00000113438_B1_33PP  TTATGAAACTCGCACCTCCAGGCCATAGAAGAGTCTTCCTTTACG
2   ENSMUST00000113438_B1_33PP  GAGGAGGGCAGCAAACGGAAATCTGGCAGACTCCGTTAAAGACAG
3   ENSMUST00000113438_B1_33PP  AAACAGCGTAATTCCCTTGTGACGTTAGAAGAGTCTTCCTTTACG
4   ENSMUST00000113438_B1_33PP  GAGGAGGGCAGCAAACGGAATTGTGCAATCTGTGACCATAAACTT
5   ENSMUST00000113438_B1_33PP  CTCCCATTATAGGGACATTCTGTTGTAGAAGAGTCTTCCTTTACG
6   ENSMUST00000113438_B1_33PP  GAGGAGGGCAGCAAACGGAACGGCTTCCCTCTGACAGCCAGGAAA
7   ENSMUST00000113438_B1_33PP  ATTCATCCCTGCACAGAATACCTTTTAGAAGAGTCTTCCTTTACG
8   ENSMUST00000113438_B1_33PP  GAGGAGGGCAGCAAACGGAAGGGGCATAAGTGGCTGGGTTGGTCT
9   ENSMUST00000113438_B1_33PP  TTTTCTTTCTTCTGGCTTCGTATCATAGAAGAGTCTTCCTTTACG
10  ENSMUST00000113438_B1_33PP  GAGGAGGGCAGCAAACGGAATGGCCGAGACAGGACAGTCCCTCAA
11  ENSMUST00000113438_B1_33PP  AACTGCCCCAGTTGCCAACTCTCCATAGAAGAGTCTTCCTTTACG
12  ENSMUST00000113438_B1_33PP  GAGGAGGGCAGCAAACGGAAGCTCTCACGGTCTGGAGGCCGCTGG
13  ENSMUST00000113438_B1_33PP  CACGTACTCGCAGGGCTGTAGGCTGTAGAAGAGTCTTCCTTTACG
14  ENSMUST00000113438_B1_33PP  GAGGAGGGCAGCAAACGGAAGGCTTGGCAGACACGCTCCGACTCT
15  ENSMUST00000113438_B1_33PP  CCTCCAAGTGTAGAGAGGACATGGTTAGAAGAGTCTTCCTTTACG
16  ENSMUST00000113438_B1_33PP  GAGGAGGGCAGCAAACGGAATCCTCCTCGGCACCTTCTGTGCCCA
17  ENSMUST00000113438_B1_33PP  TGCGCCAGCCTTCCATCTGGGGCACTAGAAGAGTCTTCCTTTACG
18  ENSMUST00000113438_B1_33PP  GAGGAGGGCAGCAAACGGAACTCGACCACAAGAGACAGAACACGA
19  ENSMUST00000113438_B1_33PP  AGCAGTAAACATTTCGATGTTTATGTAGAAGAGTCTTCCTTTACG
20  ENSMUST00000113438_B1_33PP  GAGGAGGGCAGCAAACGGAATCACAACTCAAGTCTGGGAATCGGT
21  ENSMUST00000113438_B1_33PP  TCACGGTCAGTAGGTTTGTCCAGGATAGAAGAGTCTTCCTTTACG
22  ENSMUST00000113438_B1_33PP  GAGGAGGGCAGCAAACGGAATCTGGGAGCCTCCGGCGCAGGTACT
23  ENSMUST00000113438_B1_33PP  TTTCATCCTGACACACCACCACTCGTAGAAGAGTCTTCCTTTACG
24  ENSMUST00000113438_B1_33PP  GAGGAGGGCAGCAAACGGAATCCTCGTTTTGAAATGGGTGAGCCA
25  ENSMUST00000113438_B1_33PP  CTAGGGCTGTCACTCCTGGGACGGATAGAAGAGTCTTCCTTTACG
26  ENSMUST00000113438_B1_33PP  GAGGAGGGCAGCAAACGGAACACATGGTCGCTGTAGTTGACACAC
27  ENSMUST00000113438_B1_33PP  ATCTGGGTCACACTCACTTCGATCATAGAAGAGTCTTCCTTTACG
28  ENSMUST00000113438_B1_33PP  GAGGAGGGCAGCAAACGGAACAGAACACTCTTCCTTGGCTACTGG
29  ENSMUST00000113438_B1_33PP  GAGCCTTCCACTGTCCACAGGGTGTTAGAAGAGTCTTCCTTTACG
30  ENSMUST00000113438_B1_33PP  GAGGAGGGCAGCAAACGGAACCACAAGTGGCTGAGCATGGAGTCC
31  ENSMUST00000113438_B1_33PP  CTGACGTATCTCATCCGGGTACCTTTAGAAGAGTCTTCCTTTACG
32  ENSMUST00000113438_B1_33PP  GAGGAGGGCAGCAAACGGAATAATTCACAGTCCTGGGTGTCGGTT
33  ENSMUST00000113438_B1_33PP  AGCCAGTATGGAAGGGTGGCAAGATTAGAAGAGTCTTCCTTTACG
34  ENSMUST00000113438_B1_33PP  GAGGAGGGCAGCAAACGGAACCTGTCCACAAGTGACACTGCACTG
35  ENSMUST00000113438_B1_33PP  TGCACTTCACTGCCCTTAGCTGGTATAGAAGAGTCTTCCTTTACG
36  ENSMUST00000113438_B1_33PP  GAGGAGGGCAGCAAACGGAACTATCGCTTAATCGATCTTCGCCAA
37  ENSMUST00000113438_B1_33PP  TCCGGCTTGGCCTCAGGGTCACACATAGAAGAGTCTTCCTTTACG
38  ENSMUST00000113438_B1_33PP  GAGGAGGGCAGCAAACGGAAGGAGAACTCATTGCAGCTCTGTACT
39  ENSMUST00000113438_B1_33PP  CCAGTCTCCTGTTTTCCAATGGGGATAGAAGAGTCTTCCTTTACG
40  ENSMUST00000113438_B1_33PP  GAGGAGGGCAGCAAACGGAACACCATCACAGCTTCTAGAACATTC
41  ENSMUST00000113438_B1_33PP  CACAAATTGCTCTTCTTCTCTGGGTTAGAAGAGTCTTCCTTTACG
42  ENSMUST00000113438_B1_33PP  GAGGAGGGCAGCAAACGGAAAAACTGTCATCCACCTTCTCCGTCT
43  ENSMUST00000113438_B1_33PP  TTACTCGGTCTGGGTTGACTGCTACTAGAAGAGTCTTCCTTTACG
44  ENSMUST00000113438_B1_33PP  GAGGAGGGCAGCAAACGGAAGGCTGGGGCAGCCGGTCACATCTTT
45  ENSMUST00000113438_B1_33PP  GTGCCGCACGCTTCAGTGACAGGTCTAGAAGAGTCTTCCTTTACG
46  ENSMUST00000113438_B1_33PP  GAGGAGGGCAGCAAACGGAATATCTTTCCGGGCCTTTGAGTTTAA
47  ENSMUST00000113438_B1_33PP  AATTATCTCCACCACAAATCCCACATAGAAGAGTCTTCCTTTACG
48  ENSMUST00000113438_B1_33PP  GAGGAGGGCAGCAAACGGAAATCCAAACTTGCAGTGCTTTCCAGG
49  ENSMUST00000113438_B1_33PP  GGCCCTCCATTTCTTTGGGAACACATAGAAGAGTCTTCCTTTACG
50  ENSMUST00000113438_B1_33PP  GAGGAGGGCAGCAAACGGAACTGCACTGCATCATATAGGGGCACA
51  ENSMUST00000113438_B1_33PP  CCATCCACATTATTGCACCAGAGCCTAGAAGAGTCTTCCTTTACG
52  ENSMUST00000113438_B1_33PP  GAGGAGGGCAGCAAACGGAACCTGGATGCAGGTTCATTCAGCAAG
53  ENSMUST00000113438_B1_33PP  GGGCAGTTGGGAAGGCAAAGGATAGTAGAAGAGTCTTCCTTTACG
54  ENSMUST00000113438_B1_33PP  GAGGAGGGCAGCAAACGGAAGTGTTGGTGCCATGACATGCTGGGG
55  ENSMUST00000113438_B1_33PP  ACATCCAGGGGTTGGTGTAGAAGTTTAGAAGAGTCTTCCTTTACG
56  ENSMUST00000113438_B1_33PP  GAGGAGGGCAGCAAACGGAAATCTTCCCTTGTGACCAGAACGGCT
57  ENSMUST00000113438_B1_33PP  GTCACATTTGTCCTGAGCTCTGCAGTAGAAGAGTCTTCCTTTACG
58  ENSMUST00000113438_B1_33PP  GAGGAGGGCAGCAAACGGAATGTAAGGTCCTTCCTGTTCATTATG
59  ENSMUST00000113438_B1_33PP  TTAATGTTGTCTGGGCATTGAAATTTAGAAGAGTCTTCCTTTACG
60  ENSMUST00000113438_B1_33PP  GAGGAGGGCAGCAAACGGAAGTGGTTCCATCTGTCCCTTGTGCTG
61  ENSMUST00000113438_B1_33PP  GTAGGACAGAAAGCGTTTGGTTCTTTAGAAGAGTCTTCCTTTACG
62  ENSMUST00000113438_B1_33PP  GAGGAGGGCAGCAAACGGAATTCTCCGTTTTCGCATTCTGATTTT
63  ENSMUST00000113438_B1_33PP  CCACGTCGTCAGCCAGGCTATTCCTTAGAAGAGTCTTCCTTTACG
64  ENSMUST00000113438_B1_33PP  GAGGAGGGCAGCAAACGGAATGCCTATAAATAATGTGGGGTTTGT
65  ENSMUST00000113438_B1_33PP  GTGGAGGGTTCCCTCTGAGGGGTGCTAGAAGAGTCTTCCTTTACG

In [35]:
# Export order form

idt_path = f"output/{gene_name}_idt_order.xlsx"

df_idt.to_excel(idt_path, index=False)